import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' }
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'Urban EYE',
    appSubtitle: 'Smart Civic Tracker',
    dashboard: 'Dashboard',
    reportIssue: 'Report Issue',
    newReport: 'New Report',
    myReports: 'My Tracking',
    liveMap: 'Live Map',
    alerts: 'Community Alerts',
    activity: 'City Activity',
    profile: 'Citizen Profile',
    settings: 'Settings',
    support: 'Help & Support',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    register: 'Citizen Register',
    viewProfile: 'View Profile',
    getStartedTour: "'Get Started' tour",
    privacyPolicy: 'Privacy Policy',
    accessibility: 'Accessibility',
    liveFeed: 'LIVE FEED',
    offline: 'OFFLINE',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    civicNotifications: 'Civic Notifications',
    recentAnnouncements: 'Recent Announcements',
    searchPlaceholder: 'Search city reports, wards...',
    pothole: 'Road Pothole',
    garbage: 'Garbage Overflow',
    waterLeak: 'Water Pipe Leakage',
    streetlight: 'Streetlight Outage',
    reported: 'Reported',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    verifiedCitizen: 'Verified Citizen',
    municipalAdmin: 'Municipal Admin',
    welcomeBack: 'Welcome back',
    citizen: 'Citizen',
    selectLanguage: 'Select Language / भाषा चुनें',
    themeToggled: 'Theme updated',
    coreAccess: 'Core Access',
    cityNetwork: 'City Network',
    account: 'Account',
    reportedIssues: 'Reported Issues',
    analytics: 'Analytics',
    users: 'Users',
    announcements: 'Announcements',
    liveGridActive: 'Live Grid Active',
    dashboardSubtitle: 'Real-time urban surveillance, community impact tracking, and civic resolution dispatch.',
    syncLive: 'Sync Live',
    syncing: 'Syncing...',
    communityIssues: 'Community Issues',
    inArea: 'in area',
    gpsVerified: 'GPS verified',
    verifiedResolved: 'Verified Resolved',
    civicFixes: 'fixes',
    trustScore: 'Civic Trust',
    civicKarma: 'civic karma',
    resolutionRate: 'Resolution Rate',
    citywide: 'citywide',
    mySubmissions: 'My Submissions',
    filed: 'filed',
    done: 'done',
    ptsToNextRank: 'pts to next rank',
    reportIssueAction: 'Report Issue',
    aiDetection: 'AI Detection',
    myActivity: 'My Activity',
    statusAndPdf: 'Status & PDF',
    cityScanner: 'City Scanner',
    emergencySOS: 'Emergency SOS',
    hotlines: 'Hotlines',
    communityMap: 'Community Map',
    pins: 'pins',
    myGps: 'My GPS',
    locating: 'Locating...',
    reset: 'Reset',
    live: 'Live',
    recentAreaActivity: 'Recent Activity in your Area',
    tapIncidentHint: 'Tap incident for details or official PDF',
    active: 'Active',
    filterBy: 'Filter:',
    all: 'All',
    allCategories: 'All Categories',
    potholes: 'Roads & Potholes',
    wasteGarbage: 'Garbage & Waste',
    waterLeaks: 'Water & Leaks',
    streetlights: 'Lighting',
    roadHazard: 'Road Hazard / Pothole',
    illegalWaste: 'Illegal Waste / Garbage',
    waterSewage: 'Water Leak / Sewage',
    civicInfra: 'Civic Infrastructure',
    scanningGrid: 'Scanning community grid...',
    ward: 'Ward',
    confirmExistsTitle: 'Confirm this issue exists in your area',
    inspectPdf: 'Inspect & PDF',
    noMatchingReports: 'No matching reports in your community.',
    clearFiltersHint: 'Try clearing filters or report an issue you discovered on the road.',
    resetFilters: 'Reset Filters',
    civicEngagementScore: 'Civic Engagement Score',
    pointsShort: 'PTS',
    tierCitizen: 'Tier Citizen',
    levelProgress: 'Level Progress',
    ptsTo: 'pts to',
    nextTier: 'Next Tier',
    legend: 'Legend',
    howToBoostScore: 'How to Boost Score:',
    verifiedIncidentReport: 'Verified Incident Report',
    municipalFixCompleted: 'Municipal Fix Completed',
    confirmCommunityHazard: 'Confirm Community Hazard',
    activeAlerts: 'Active Alerts',
    alertsCount: 'Alerts',
    allClearSector: 'All Clear in Sector',
    allClearDesc: 'No critical municipal hazard warnings or route closures.',
    proTipsTitle: 'Pro Tips for Faster Resolution',
    tip1Title: 'Capture Wide Angle:',
    tip1Desc: 'Include road dividers or nearby storefronts to help field teams locate the issue.',
    tip2Title: 'Verify Map Pin:',
    tip2Desc: 'Fine-tune the GPS pin on the map preview if reporting after leaving the site.',
    tip3Title: 'Download Official PDF:',
    tip3Desc: 'Use the generated PDF dispatch report if escalating to your local RWA or ward councillor.',
    emergencyModalTitle: 'Emergency Civic Hotlines',
    emergencyModalSubtitle: 'Direct dial for municipal and emergency services',
    close: 'Close',
    policeHelpline: 'National Emergency / Police',
    policeDesc: 'Police, ambulance & disaster control',
    fireHelpline: 'Fire Control Room',
    fireDesc: 'Fire hazards & rescue services',
    pwdHelpline: 'Municipal / PWD Road Control',
    pwdDesc: 'Sinkholes, road collapse & fallen trees',
    waterHelpline: 'Water Supply & Main Pipeline',
    waterDesc: 'Major water line rupture & flooding',
    electricityHelpline: 'Electricity Board / Live Wire',
    electricityDesc: 'High-voltage wire hazard & transformer fire',
    ambassadorBadge: 'Civic Ambassador',
    guardianBadge: 'Verified Guardian',
    activeBadge: 'Active Citizen',
    contributorBadge: 'Community Contributor',
    platinumTier: 'Platinum',
    goldTier: 'Gold',
    silverTier: 'Silver',
    bronzeTier: 'Bronze',
    mySubmittedReports: 'My Submitted Reports',
    liveTracking: 'LIVE TRACKING',
    reportsSubtitle: 'Track real-time status changes and community confirmations for your reported infrastructure issues',
    reportNewIssue: 'Report New Issue',
    allReports: 'All Reports',
    noReportsFound: 'No reports found',
    noReportsSubmittedYet: "You haven't submitted any infrastructure issue reports yet.",
    submitFirstReport: 'Submit Your First Report',
    viewCard: 'View',
    noImageCaptured: 'NO IMAGE CAPTURED',
    reportsCount: 'reports',
    reportSingle: 'report',
    emergencyServices: 'Emergency Services',
    emergencyHelplines: 'Municipal Emergency Helplines',
    police: 'Police Control Room',
    ambulance: 'Ambulance & Medical',
    fireDepartment: 'Fire & Rescue',
    municipalHelpline: 'Civic Disaster Cell',
    inspectDetails: 'Inspect Details',
    confirmIssue: 'Confirm Issue',
    confirmed: 'Confirmed',
    activeWatch: 'Active Watch',
    citizenProfile: 'Citizen Profile',
    profileSubtitle: 'Manage identity, track civic score, and view dispatch history',
    editProfile: 'Edit Profile',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully!',
    exportRecord: 'Export Record',
    fullName: 'Full Name',
    contactPhone: 'Contact Phone',
    wardNeighborhood: 'Municipal Ward / Neighborhood',
    activeSince: 'Active since',
    civicStatement: 'Civic Statement',
    systemStatus: 'System Status',
    adminCommand: 'Admin Command',
    civicTierRank: 'Civic Tier Rank',
    tierMilestone: 'Tier Milestone',
    ptsToLevelUp: 'pts to Level Up',
    citizenPreferences: 'Citizen Preferences',
    emailReportUpdates: 'Email Report Updates',
    emailUpdatesDesc: 'Alerts when city resolves issues',
    criticalSmsAlerts: 'Critical SMS Alerts',
    smsAlertsDesc: 'High-priority road & flood hazard alerts',
    locationAutoTag: 'Location Auto-Tag',
    locationAutoTagDesc: 'Auto-fill street name on photo upload',
    totalReports: 'Total Reports',
    submittedByYou: 'Submitted by you',
    fixRate: 'fix rate',
    trustScoreLabel: 'Trust Score',
    reliabilityRating: 'Reliability rating',
    endorsements: 'Endorsements',
    communityConfirmations: 'Community confirmations',
    civicAchievementsBadges: 'Civic Achievements & Badges',
    unlocked: 'Unlocked',
    myReportedIncidents: 'My Reported Incidents',
    trackResolutionDesc: 'Track resolution status and download official municipal PDFs',
    loadingCivicHistory: 'Loading civic history...',
    noIncidentsFound: 'No incident reports under this filter.',
    foundHazardQuestion: 'Found a road hazard, streetlight outage, or water leak in your neighborhood?',
    reportAnIssue: 'Report an Issue',
    exploreLiveMap: 'Explore Live Community Map',
    exploreMapDesc: 'View real-time pins and municipal response teams',
    submitRoadHazard: 'Submit New Road Hazard',
    submitHazardDesc: 'Instant AI triage, geolocation, and dispatch',
    firstResponder: 'First Responder',
    firstResponderDesc: 'Submit your first verified incident report',
    potholeHunter: 'Pothole Hunter',
    potholeHunterDesc: 'Report 3 or more road surface hazards',
    wasteBuster: 'Waste Buster',
    wasteBusterDesc: 'Report illegal dumping or uncollected garbage',
    aquaSentinel: 'Aqua Sentinel',
    aquaSentinelDesc: 'Report water main breaks or sewage leaks',
    nightWatch: 'Night Watch',
    nightWatchDesc: 'Report faulty streetlights to improve safety',
    civicPillar: 'Civic Pillar',
    civicPillarDesc: 'Reach a civic trust score of 90 or higher',
    intelligentIncidentReporting: 'Intelligent Incident Reporting',
    reportPageSubtitle: 'Snap a photo or upload an image. Urban EYE will automatically pinpoint the location, analyze the infrastructure defect with AI, and dispatch work orders directly to municipal departments.',
    trackPastReports: 'Track Past Reports',
    incidentDispatched: 'Incident Dispatched Successfully!',
    incidentDispatchedDesc: 'Municipal authority has been notified with high-priority assignment.',
    categoryLabel: 'CATEGORY',
    severityLabel: 'SEVERITY',
    assignedDept: 'ASSIGNED DEPT',
    citizenReportsCount: 'CITIZEN REPORTS',
    generatedComplaintLetter: 'Generated Formal Municipal Grievance Letter',
    editLetter: 'Edit Letter',
    saveUpdates: 'Save Updates',
    downloadPdfReport: 'Download PDF Report',
    generatingPdf: 'Generating PDF...',
    inspectAiDetails: 'Inspect AI Details',
    viewInMyReports: 'View in My Reports',
    reportAnotherIncident: 'Report Another Incident',
    uploadEvidencePhoto: 'Upload Evidence Photo',
    changePhoto: 'Change Photo',
    takeNewPhoto: 'Take New Photo',
    tapToSelectPhoto: 'Tap to select or drop incident photo',
    gpsAutoExtraction: 'Automatic GPS extraction & client-side compression enabled',
    browseFiles: 'Browse Files',
    takePhoto: 'Take Photo',
    selectDefectCategory: 'Select Defect Category',
    autoClassifiedHint: 'Auto-classified if unsure',
    roadsAndWorks: 'Roads & Works',
    sanitation: 'Sanitation',
    waterSupply: 'Water Supply',
    electricalDept: 'Electrical Dept',
    submitIncidentReport: 'Submit Incident Report',
    runningAiTriage: 'Running AI Triage & Dispatch...',
    submitNotice: 'Upon submission, our AI will cluster nearby reports within 50m to avoid duplicates, route to municipal engineers, and trigger verified email dispatches.',
    pinpointLocation: 'Pinpoint Exact Location',
    dragPinHint: 'Drag the pin or click on the map to position',
    realtimeAddressSync: 'Real-time address sync',
    detectedLandmark: 'Detected Landmark & Street Address',
    autoFilledFromPin: 'Auto-filled from pin',
    latitude: 'Latitude',
    longitude: 'Longitude',
    cityActivityTitle: 'City Activity',
    cityActivitySubtitle: 'Live feed of community reports and city crew resolutions.',
    loadOlderActivity: 'Load Older Activity ↓',
    todaysImpact: "Today's Impact",
    newReportsStat: 'New Reports',
    issuesResolved: 'Issues Resolved',
    activeCityCrews: 'Active City Crews',
    anonymousCitizen: 'Anonymous Citizen',
    cityCrew: 'City Crew',
    cityAdmin: 'City Admin',
    near: 'near',
    justNow: 'Just now',
    time45mAgo: '45 mins ago',
    time2hAgo: '2 hours ago',
    time3hAgo: '3 hours ago',
    reportedRoadHazard: 'reported a road hazard',
    resolvedStreetlightOutage: 'resolved a streetlight outage',
    reportedWaterLeak: 'reported a water leak',
    escalatedInfraIssue: 'escalated an infrastructure issue',
    communityAlertsTitle: 'Community Alerts',
    communityAlertsSubtitle: 'Stay informed with real-time city broadcasts and emergency updates.',
    liveNetwork: 'Live Network',
    allCaughtUp: "You're all caught up",
    time10mAgo: '10 mins ago',
    time1dAgo: '1 day ago',
    alert1Title: 'Major Road Closure: Main St.',
    alert1Desc: 'Main St will be closed from 4th Ave to 8th Ave for emergency water main repairs. Please use alternate routes.',
    alert2Title: 'Power Outage Resolved',
    alert2Desc: 'Power has been fully restored to the Northside district. Thank you for your patience.',
    alert3Title: 'Scheduled Maintenance',
    alert3Desc: 'City park facilities will undergo routine maintenance this weekend. Some areas may be restricted.',
    preferences: 'Preferences',
    settingsSubtitle: 'Manage your Urban EYE account settings and notifications.',
    notificationsTitle: 'Notifications',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Receive alerts directly on your device.',
    emailUpdates: 'Email Updates',
    emailUpdatesPrefDesc: 'Weekly summaries and critical alerts.',
    privacyAndData: 'Privacy & Data',
    anonymousReporting: 'Anonymous Reporting',
    anonymousReportingDesc: 'Hide your name from public community reports.',
    shareLocationData: 'Share Location Data',
    shareLocationDataDesc: 'Help city planners map infrastructure hotspots.',
    appPreferences: 'App Preferences',
    theme: 'Theme',
    systemDefaultDark: 'System Default (Dark)',
    highContrast: 'High Contrast',
    language: 'Language',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'Permanently delete your account and all associated report history. This action cannot be undone.',
    saved: 'Saved!',
    supportTitle: 'Help & Support',
    emergency: 'Emergency',
    policeFireMedical: 'Police / Fire / Medical',
    nonEmergencyPolice: 'Non-Emergency Police',
    contactUs: 'Contact Us',
    emailSupport: 'Email Support',
    liveChat: 'Live Chat',
    liveChatHours: 'Available 9AM - 5PM',
    faqTitle: 'Frequently Asked Questions',
    sendFeedback: 'Send Feedback',
    sendFeedbackSubtitle: 'Found a bug or have a suggestion? Let our developers know.',
    message: 'Message',
    describeIssuePlaceholder: 'Describe your issue or suggestion...',
    submitFeedback: 'Submit Feedback',
    faq1Q: 'How do I track a report I submitted?',
    faq1A: "Navigate to the 'My Tracking' section in the sidebar. There you will see a list of all your submitted reports along with their current resolution status (Pending, In-Progress, or Resolved).",
    faq2Q: 'Will my identity be revealed to the public?',
    faq2A: "No. Unless you change your privacy settings in the Preferences menu, all reports submitted to the community feed appear as 'Anonymous Citizen'.",
    faq3Q: 'What should I do in a severe emergency?',
    faq3A: 'Urban EYE is for non-emergency infrastructure reporting only. For all immediate threats to life, property, or public safety, please call emergency services immediately.',
    incidentInspection: 'Incident Inspection',
    officialDispatch: 'Official Municipal Dispatch',
    deleteReport: 'Delete Report',
    downloadPdf: 'Download PDF',
    generating: 'Generating...',
    editFormalLetter: 'Edit Complaint Letter',
    saveFormalLetter: 'Save Letter',
    resetOfficialTemplate: 'Reset Template',
    copyLetter: 'Copy Letter',
    copied: 'Copied!',
    status: 'Status',
    assignedDepartment: 'Assigned Department',
    reportedBy: 'Reported By',
    dateReported: 'Date Reported',
    locationCoordinates: 'Location Coordinates',
    viewOnGoogleMaps: 'View on Google Maps',
    verifiedReports: 'Verified Reports',
    incidentRecord: 'Record',
    severityLevel: 'SEVERITY LEVEL',
    incidentStatus: 'INCIDENT STATUS',
    verifiableDispatchSent: 'VERIFIABLE DISPATCH EMAIL SENT',
    openEmailPreview: 'Open Email Preview',
    editLetterHelp: 'You can edit any part of this formal complaint letter, add specific landmark notes, or adjust the problem description before exporting the PDF.',
    adminStatusTriage: 'ADMINISTRATIVE STATUS TRIAGE',
    markNew: 'Mark New',
    markAssigned: 'Mark Assigned',
    closeInspector: 'Close Inspector',
    signInSubtitle: 'Sign in to your citizen portal to continue.',
    emailLogin: 'Email Login',
    phoneOtp: 'Phone (OTP)',
    emailAddress: 'Email Address',
    password: 'Password',
    phoneNumber: 'Phone Number',
    oneTimePassword: 'One-Time Password',
    sendVerificationCode: 'Send Verification Code',
    verifyAndSignIn: 'Verify & Sign In',
    newToUrbanEye: 'New to Urban EYE?',
    createAccount: 'Create account',
    officialAccess: 'Official Access',
    empoweringCitizens: 'Empowering citizens.',
    improvingCities: 'Improving cities.',
    joinThousands: 'Join thousands of residents actively monitoring and reporting urban infrastructure issues in real-time.',
    secureConnection: 'Secure & encrypted connection',
    citizenRegistration: 'Citizen Registration',
    alreadyRegistered: 'Already have an account?',
    viewAllAlerts: 'View All Community Alerts →',
    pinsLive: 'Pins Live',
    myLocation: 'My Location',
    radarOn: 'Radar ON',
    radarOff: 'Radar OFF',
    showCards: 'Show Cards',
    fullMap: 'Full Map',
    feed: 'Feed',
    liveIncidentFeed: 'Live Incident Feed',
    noIncidentsForFilter: 'No incidents found for current filter.',
    myReportsAndPdf: 'My Reports & PDF',
    inspectIncidentDetails: 'Inspect Incident Details',
    clickMapToPin: 'Click map to pin',
    severityTitle: 'SEVERITY',
    allSeverities: 'All Severities',
    highSeverity: 'High Severity',
    mediumSeverity: 'Medium Severity',
    lowSeverity: 'Low Severity',
    viewPins: 'VIEW PINS',
    heatmap: 'HEATMAP',
    allIssues: 'All Incidents',
    confirmSignOutTitle: 'Do you really want to sign out?',
    confirmSignOutDesc: 'Are you sure you want to end your current session? You will need to sign in again to access your dashboard and reports.',
    yesSignOut: 'Yes, Sign Out',
    noCancel: 'No, Keep Me In',
    signOutSecurely: 'Sign Out Securely',
    continueWithGoogle: 'Continue with Google',
    googleSignIn: 'Sign in with Google',
    googleSignUp: 'Sign up with Google',
    orContinueWith: 'Or continue with',
    orRegisterWithEmail: 'Or register with email',
    googleAuthSuccess: 'Google Authentication Successful',
    googleAuthFailed: 'Google Authentication Failed',
    verifyEmailTitle: 'Verify Your Email Address',
    verifyEmailSubtitle: 'We sent a 6-digit verification code to',
    enterOtpCode: 'Enter 6-digit OTP Code',
    verifyAndCreate: 'Verify & Create Account',
    resendOtp: 'Resend Code',
    otpResent: 'Verification code resent successfully!',
    invalidOtp: 'Invalid or expired OTP code. Please check and try again.',
    verifyingOtp: 'Verifying code...',
    didNotReceiveCode: "Didn't receive the code?",
    resendIn: 'Resend in',
    allAlerts: 'All Alerts',
    criticalEmergency: 'Critical / Emergency',
    civicAdvisories: 'Civic Advisories',
    serviceRestored: 'Service Restored',
    publicNotices: 'Public Notices',
    searchAlertsPlaceholder: 'Search alerts by keyword, ward or topic...',
    listenAlert: 'Listen',
    listening: 'Playing...',
    stopListening: 'Stop',
    shareAlert: 'Share',
    alertCopied: 'Alert details copied to clipboard!',
    staySafeAcknowledged: 'Acknowledged',
    acknowledgedBy: 'citizens acknowledged',
    affectedArea: 'Affected Area',
    emergencyHotline: 'Emergency Hotline',
    clearAllNotifs: 'Clear all',
    noNotifications: 'No new civic notifications',
    allCaughtUpDesc: 'You are up-to-date with all community notices.'
  },
  hi: {
    appTitle: 'अर्बन आई (Urban EYE)',
    appSubtitle: 'स्मार्ट नागरिक एवं शहरी अवसंरचना ट्रैकर',
    dashboard: 'डैशबोर्ड',
    reportIssue: 'समस्या रिपोर्ट करें',
    newReport: 'नई रिपोर्ट दर्ज करें',
    myReports: 'मेरी ट्रैकिंग',
    liveMap: 'लाइव शहर मानचित्र',
    alerts: 'सामुदायिक अलर्ट',
    activity: 'शहर की गतिविधियाँ',
    profile: 'नागरिक प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    support: 'सहायता एवं सहयोग',
    signOut: 'साइन आउट',
    signIn: 'साइन इन करें',
    register: 'नागरिक पंजीकरण',
    viewProfile: 'प्रोफ़ाइल देखें',
    getStartedTour: "'शुरुआती' परिचय यात्रा",
    privacyPolicy: 'गोपनीयता नीति',
    accessibility: 'सुलभता विकल्प (Accessibility)',
    liveFeed: 'लाइव फ़ीड',
    offline: 'ऑफ़लाइन',
    notifications: 'सूचनाएं',
    markAllRead: 'सभी को पढ़ा हुआ मार्क करें',
    civicNotifications: 'नागरिक अधिसूचनाएं',
    recentAnnouncements: 'हालिया नगर निगम घोषणाएं',
    searchPlaceholder: 'शहर की समस्याएं, वार्ड खोजें...',
    pothole: 'सड़क का गड्ढा',
    garbage: 'कचरा डंपिंग',
    waterLeak: 'पेयजल पाइपलाइन रिसाव',
    streetlight: 'खराब स्ट्रीटलाइट',
    reported: 'दर्ज हुआ',
    inProgress: 'कार्य प्रगति पर',
    resolved: 'समाधान संपन्न',
    critical: 'अति गंभीर',
    high: 'उच्च प्राथमिकता',
    medium: 'मध्यम',
    low: 'सामान्य',
    verifiedCitizen: 'प्रमाणित नागरिक',
    municipalAdmin: 'नगर निगम प्रशासक',
    welcomeBack: 'स्वागत है',
    citizen: 'नागरिक',
    selectLanguage: 'भाषा चुनें (Select Language)',
    themeToggled: 'थीम परिवर्तित हुई',
    coreAccess: 'मुख्य सेवाएँ',
    cityNetwork: 'शहरी नेटवर्क',
    account: 'खाता',
    reportedIssues: 'दर्ज समस्याएं',
    analytics: 'एनालिटिक्स',
    users: 'उपयोगकर्ता',
    announcements: 'घोषणाएं',
    liveGridActive: 'लाइव ग्रिड सक्रिय',
    dashboardSubtitle: 'वास्तविक समय शहरी निगरानी, सामुदायिक प्रभाव ट्रैकिंग और नागरिक समस्या समाधान।',
    syncLive: 'लाइव सिंक करें',
    syncing: 'सिंक हो रहा है...',
    communityIssues: 'सामुदायिक समस्याएं',
    inArea: 'वार्ड / क्षेत्र में',
    gpsVerified: 'GPS द्वारा सत्यापित',
    verifiedResolved: 'सत्यापित समाधान',
    civicFixes: 'सुधार',
    trustScore: 'नागरिक विश्वास',
    civicKarma: 'नागरिक कर्म',
    resolutionRate: 'समाधान दर',
    citywide: 'पूरे शहर में',
    mySubmissions: 'मेरी प्रस्तुतियां',
    filed: 'दर्ज',
    done: 'सम्पन्न',
    ptsToNextRank: 'अंक अगले स्तर हेतु',
    reportIssueAction: 'समस्या रिपोर्ट करें',
    aiDetection: 'AI पहचान',
    myActivity: 'मेरी गतिविधि',
    statusAndPdf: 'स्थिति एवं PDF',
    cityScanner: 'सिटी स्कैनर',
    emergencySOS: 'आपातकालीन SOS',
    hotlines: 'हेल्पलाइन नंबर',
    communityMap: 'सामुदायिक मानचित्र',
    pins: 'स्थान',
    myGps: 'मेरा GPS',
    locating: 'खोज रहा है...',
    reset: 'रीसेट करें',
    live: 'लाइव',
    recentAreaActivity: 'आपके क्षेत्र की हालिया गतिविधियां',
    tapIncidentHint: 'विवरण या आधिकारिक PDF के लिए समस्या पर टैप करें',
    active: 'सक्रिय',
    filterBy: 'फिल्टर:',
    all: 'सभी',
    allCategories: 'सभी श्रेणियां',
    potholes: 'सड़क के गड्ढे',
    wasteGarbage: 'कचरा / डंप',
    waterLeaks: 'पानी का रिसाव',
    streetlights: 'स्ट्रीटलाइट्स',
    roadHazard: 'सड़क का गड्ढा / बाधा',
    illegalWaste: 'कचरे का ढेर / डंप',
    waterSewage: 'पानी का रिसाव / सीवेज',
    civicInfra: 'नागरिक बुनियादी ढांचा',
    scanningGrid: 'सामुदायिक ग्रिड स्कैन हो रहा है...',
    ward: 'वार्ड',
    confirmExistsTitle: 'पुष्टि करें कि यह समस्या आपके क्षेत्र में मौजूद है',
    inspectPdf: 'जांचें एवं PDF',
    noMatchingReports: 'आपके समुदाय में कोई मेल खाती रिपोर्ट नहीं मिली।',
    clearFiltersHint: 'फ़िल्टर हटाएं या सड़क पर देखी गई कोई समस्या रिपोर्ट करें।',
    resetFilters: 'फ़िल्टर रीसेट करें',
    civicEngagementScore: 'नागरिक सहभागिता स्कोर',
    pointsShort: 'अंक',
    tierCitizen: 'श्रेणी नागरिक',
    levelProgress: 'स्तर प्रगति',
    ptsTo: 'अंक शेष:',
    nextTier: 'अगला स्तर',
    legend: 'लीजेंड',
    howToBoostScore: 'स्कोर कैसे बढ़ाएं:',
    verifiedIncidentReport: 'सत्यापित घटना रिपोर्ट',
    municipalFixCompleted: 'नगर निगम सुधार पूर्ण',
    confirmCommunityHazard: 'सामुदायिक खतरे की पुष्टि',
    activeAlerts: 'सक्रिय अलर्ट',
    alertsCount: 'अलर्ट',
    allClearSector: 'सेक्टर में सब सुरक्षित',
    allClearDesc: 'कोई गंभीर नगर निगम चेतावनी या मार्ग रुकावट नहीं है।',
    proTipsTitle: 'शीघ्र समाधान के लिए सुझाव',
    tip1Title: 'विस्तृत कोण से फोटो लें:',
    tip1Desc: 'सड़क डिवाइडर या आसपास की दुकानों को शामिल करें जिससे टीम स्थान पहचान सके।',
    tip2Title: 'मानचित्र पिन सत्यापित करें:',
    tip2Desc: 'यदि घटना स्थल छोड़ने के बाद रिपोर्ट कर रहे हों तो मैप पर पिन सही करें।',
    tip3Title: 'आधिकारिक PDF डाउनलोड करें:',
    tip3Desc: 'स्थानीय आरडब्ल्यूए या पार्षद को प्रस्तुत करने हेतु तैयार पीडीएफ का उपयोग करें।',
    emergencyModalTitle: 'आपातकालीन नागरिक हेल्पलाइन',
    emergencyModalSubtitle: 'नगर निगम एवं आपातकालीन सेवाओं के लिए सीधा डायल करें',
    close: 'बंद करें',
    policeHelpline: 'राष्ट्रीय आपातकाल / पुलिस',
    policeDesc: 'पुलिस, एम्बुलेंस एवं आपदा नियंत्रण',
    fireHelpline: 'अग्निशमन नियंत्रण कक्ष',
    fireDesc: 'आग का खतरा एवं बचाव सेवाएं',
    pwdHelpline: 'नगर निगम / PWD रोड कंट्रोल',
    pwdDesc: 'धंसी सड़क, गड्ढे एवं गिरे हुए पेड़',
    waterHelpline: 'जल आपूर्ति एवं मुख्य पाइपलाइन',
    waterDesc: 'पाइपलाइन टूटना एवं जलभराव',
    electricityHelpline: 'विद्युत बोर्ड / खुला तार',
    electricityDesc: 'हाई-वोल्टेज खुला तार एवं ट्रांसफार्मर में आग',
    ambassadorBadge: 'नागरिक दूत',
    guardianBadge: 'प्रमाणित संरक्षक',
    activeBadge: 'सक्रिय नागरिक',
    contributorBadge: 'समुदाय योगदानकर्ता',
    platinumTier: 'प्लैटिनम',
    goldTier: 'स्वर्ण (Gold)',
    silverTier: 'रजत (Silver)',
    bronzeTier: 'कांस्य (Bronze)',
    mySubmittedReports: 'मेरी प्रस्तुत रिपोर्टें',
    liveTracking: 'लाइव ट्रैकिंग',
    reportsSubtitle: 'अपनी दर्ज की गई समस्याओं की स्थिति और सामुदायिक पुष्टि वास्तविक समय में ट्रैक करें',
    reportNewIssue: 'नई समस्या दर्ज करें',
    allReports: 'सभी रिपोर्ट',
    noReportsFound: 'कोई रिपोर्ट नहीं मिली',
    noReportsSubmittedYet: 'आपने अभी तक कोई समस्या रिपोर्ट नहीं दर्ज की है।',
    submitFirstReport: 'अपनी पहली रिपोर्ट दर्ज करें',
    viewCard: 'देखें',
    noImageCaptured: 'कोई फोटो उपलब्ध नहीं',
    reportsCount: 'रिपोर्टें',
    reportSingle: 'रिपोर्ट',
    emergencyServices: 'आपातकालीन सेवाएं',
    emergencyHelplines: 'नगर निगम आपातकालीन हेल्पलाइन',
    police: 'पुलिस नियंत्रण कक्ष',
    ambulance: 'एम्बुलेंस एवं चिकित्सा',
    fireDepartment: 'अग्निशमन एवं बचाव',
    municipalHelpline: 'आपदा एवं नागरिक सेल',
    inspectDetails: 'विवरण देखें',
    confirmIssue: 'पुष्टि करें',
    confirmed: 'पुष्टीकृत',
    activeWatch: 'सक्रिय निगरानी',
    citizenProfile: 'नागरिक प्रोफ़ाइल',
    profileSubtitle: 'पहचान प्रबंधित करें, नागरिक स्कोर ट्रैक करें और प्रेषण इतिहास देखें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    cancel: 'रद्द करें',
    saveChanges: 'परिवर्तन सहेजें',
    saving: 'सहेजा जा रहा है...',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
    exportRecord: 'रिकॉर्ड निर्यात करें (JSON)',
    fullName: 'पूरा नाम',
    contactPhone: 'संपर्क फ़ोन नंबर',
    wardNeighborhood: 'नगर पालिका वार्ड / मोहल्ला',
    activeSince: 'सक्रियता प्रारंभ',
    civicStatement: 'नागरिक संकल्प / वक्तव्य',
    systemStatus: 'सिस्टम स्थिति',
    adminCommand: 'प्रशासक कमांड',
    civicTierRank: 'नागरिक श्रेणी रैंक',
    tierMilestone: 'अगला स्तर लक्ष्य',
    ptsToLevelUp: 'अंक स्तर वृद्धि हेतु',
    citizenPreferences: 'नागरिक प्राथमिकताएं',
    emailReportUpdates: 'ईमेल रिपोर्ट अपडेट',
    emailUpdatesDesc: 'जब नगर निगम समस्या हल करे तो सूचना मिले',
    criticalSmsAlerts: 'महत्वपूर्ण एसएमएस अलर्ट',
    smsAlertsDesc: 'उच्च प्राथमिकता सड़क व जलभराव चेतावनी',
    locationAutoTag: 'स्थान स्वतः-टैग',
    locationAutoTagDesc: 'फोटो अपलोड पर सड़क का नाम स्वतः भरें',
    totalReports: 'कुल दर्ज रिपोर्ट',
    submittedByYou: 'आपके द्वारा प्रस्तुत',
    fixRate: 'समाधान दर',
    trustScoreLabel: 'विश्वसनीयता स्कोर',
    reliabilityRating: 'नागरिक विश्वसनीयता रेटिंग',
    endorsements: 'सामुदायिक समर्थन',
    communityConfirmations: 'नागरिक पुष्टियाँ',
    civicAchievementsBadges: 'नागरिक उपलब्धियाँ एवं बैज',
    unlocked: 'अनलॉक हुआ',
    myReportedIncidents: 'मेरी दर्ज की गई समस्याएं',
    trackResolutionDesc: 'समाधान स्थिति ट्रैक करें और आधिकारिक नगर पालिका पीडीएफ डाउनलोड करें',
    loadingCivicHistory: 'नागरिक इतिहास लोड हो रहा है...',
    noIncidentsFound: 'इस फ़िल्टर में कोई रिपोर्ट नहीं मिली।',
    foundHazardQuestion: 'क्या आपके क्षेत्र में कोई सड़क का गड्ढा, खराब लाइट या पानी का रिसाव दिखा?',
    reportAnIssue: 'समस्या दर्ज करें',
    exploreLiveMap: 'लाइव समुदाय मानचित्र देखें',
    exploreMapDesc: 'रीयल-टाइम पिन और नगर निगम टीमों की स्थिति देखें',
    submitRoadHazard: 'नई सड़क समस्या दर्ज करें',
    submitHazardDesc: 'तत्काल एआई वर्गीकरण, जियोलोकेशन एवं प्रेषण',
    firstResponder: 'प्रथम उत्तरदाता (First Responder)',
    firstResponderDesc: 'अपनी पहली सत्यापित रिपोर्ट दर्ज करें',
    potholeHunter: 'पॉटहोल हंटर',
    potholeHunterDesc: '3 या अधिक सड़क गड्ढों की रिपोर्ट दर्ज करें',
    wasteBuster: 'कचरा निवारक (Waste Buster)',
    wasteBusterDesc: 'अवैध कचरा डंपिंग की रिपोर्ट करें',
    aquaSentinel: 'जल रक्षक (Aqua Sentinel)',
    aquaSentinelDesc: 'पाइपलाइन लीकेज या सीवेज ओवरफ्लो रिपोर्ट करें',
    nightWatch: 'रात्रि प्रहरी (Night Watch)',
    nightWatchDesc: 'सड़क सुरक्षा हेतु खराब स्ट्रीटलाइट रिपोर्ट करें',
    civicPillar: 'नागरिक स्तंभ (Civic Pillar)',
    civicPillarDesc: '90 या अधिक नागरिक ट्रस्ट स्कोर अर्जित करें',
    intelligentIncidentReporting: 'इंटेलिजेंट समस्या रिपोर्टिंग',
    reportPageSubtitle: 'फोटो खींचें या अपलोड करें। अर्बन आई स्वचालित रूप से जीपीएस दर्ज करेगा, एआई द्वारा समस्या का विश्लेषण करेगा और सीधे संबंधित नगर पालिका विभाग को भेजेगा।',
    trackPastReports: 'पिछली रिपोर्ट ट्रैक करें',
    incidentDispatched: 'समस्या सफलतापूर्वक प्रेषित हुई!',
    incidentDispatchedDesc: 'नगर निगम प्राधिकरण को उच्च प्राथमिकता के साथ सूचित कर दिया गया है।',
    categoryLabel: 'श्रेणी (CATEGORY)',
    severityLabel: 'गंभीरता (SEVERITY)',
    assignedDept: 'आवंटित विभाग',
    citizenReportsCount: 'नागरिक रिपोर्ट',
    generatedComplaintLetter: 'उत्पन्न आधिकारिक नगर निगम शिकायत पत्र',
    editLetter: 'पत्र संपादित करें',
    saveUpdates: 'अपडेट सहेजें',
    downloadPdfReport: 'पीडीएफ रिपोर्ट डाउनलोड करें',
    generatingPdf: 'पीडीएफ तैयार हो रही है...',
    inspectAiDetails: 'एआई विवरण देखें',
    viewInMyReports: 'मेरी रिपोर्ट में देखें',
    reportAnotherIncident: 'एक और समस्या दर्ज करें',
    uploadEvidencePhoto: 'साक्ष्य फोटो अपलोड करें',
    changePhoto: 'फोटो बदलें',
    takeNewPhoto: 'नया फोटो खींचें',
    tapToSelectPhoto: 'समस्या का फोटो चुनने या खींचने के लिए टैप करें',
    gpsAutoExtraction: 'स्वचालित जीपीएस निष्कर्षण और छवि संपीड़न सक्षम',
    browseFiles: 'फ़ाइलें चुनें',
    takePhoto: 'फोटो खींचें',
    selectDefectCategory: 'समस्या की श्रेणी चुनें',
    autoClassifiedHint: 'निश्चित न होने पर एआई स्वतः वर्गीकृत करेगा',
    roadsAndWorks: 'सड़क एवं निर्माण विभाग',
    sanitation: 'स्वच्छता विभाग',
    waterSupply: 'जल आपूर्ति विभाग',
    electricalDept: 'विद्युत विभाग',
    submitIncidentReport: 'शिकायत दर्ज करें',
    runningAiTriage: 'एआई विश्लेषण एवं प्रेषण जारी है...',
    submitNotice: 'प्रस्तुत करने पर, डुप्लिकेट से बचने के लिए एआई 50 मीटर के भीतर की रिपोर्टों को समूहित करेगा और इंजीनियरों को भेजेगा।',
    pinpointLocation: 'सटीक स्थान इंगित करें',
    dragPinHint: 'पिन खींचें या मानचित्र पर टैप करके स्थान तय करें',
    realtimeAddressSync: 'रीयल-टाइम पता समन्वय',
    detectedLandmark: 'पहचाना गया लैंडमार्क और सड़क का पता',
    autoFilledFromPin: 'पिन से स्वतः भरा गया',
    latitude: 'अक्षांश (Latitude)',
    longitude: 'देशांतर (Longitude)',
    cityActivityTitle: 'शहर की गतिविधियाँ',
    cityActivitySubtitle: 'नागरिक रिपोर्टों और नगर पालिका टीमों के कार्य की लाइव फ़ीड।',
    loadOlderActivity: 'पुरानी गतिविधियाँ देखें ↓',
    todaysImpact: 'आज का प्रभाव',
    newReportsStat: 'नई रिपोर्ट दर्ज',
    issuesResolved: 'समस्याएं हल हुईं',
    activeCityCrews: 'सक्रिय नगर निगम टीमें',
    anonymousCitizen: 'गुमनाम नागरिक',
    cityCrew: 'नगर पालिका टीम',
    cityAdmin: 'नगर व्यवस्थापक (Admin)',
    near: 'के पास',
    justNow: 'अभी-अभी',
    time45mAgo: '45 मिनट पहले',
    time2hAgo: '2 घंटे पहले',
    time3hAgo: '3 घंटे पहले',
    reportedRoadHazard: 'ने सड़क के गड्ढे की शिकायत दर्ज की',
    resolvedStreetlightOutage: 'ने स्ट्रीटलाइट की समस्या का समाधान किया',
    reportedWaterLeak: 'ने पानी रिसाव की शिकायत दर्ज की',
    escalatedInfraIssue: 'ने बुनियादी ढांचे की समस्या को आगे बढ़ाया',
    communityAlertsTitle: 'सामुदायिक अलर्ट',
    communityAlertsSubtitle: 'रीयल-टाइम शहर प्रसारण और आपातकालीन अलर्ट से अवगत रहें।',
    liveNetwork: 'लाइव नेटवर्क',
    allCaughtUp: 'आप पूरी तरह अपडेट हैं',
    time10mAgo: '10 मिनट पहले',
    time1dAgo: '1 दिन पहले',
    alert1Title: 'सड़क बंद: मुख्य मार्ग (Main St.)',
    alert1Desc: 'मुख्य जल पाइपलाइन मरम्मत के कारण मेन स्ट्रीट 4th Ave से 8th Ave तक बंद रहेगी। कृपया वैकल्पिक मार्गों का उपयोग करें।',
    alert2Title: 'विद्युत आपूर्ति बहाल हुई',
    alert2Desc: 'नॉर्थसाइड क्षेत्र में बिजली आपूर्ति पूरी तरह से बहाल कर दी गई है। आपके सहयोग हेतु धन्यवाद।',
    alert3Title: 'नियोजित रखरखाव कार्य',
    alert3Desc: 'इस सप्ताहांत शहर के पार्क में नियमित रखरखाव कार्य किया जाएगा। कुछ क्षेत्र सीमित रह सकते हैं।',
    preferences: 'प्राथमिकताएं (Settings)',
    settingsSubtitle: 'अपने अर्बन आई खाते की सेटिंग्स और सूचनाएं प्रबंधित करें।',
    notificationsTitle: 'सूचनाएं (Notifications)',
    pushNotifications: 'पुश सूचनाएं (Push Notifications)',
    pushNotificationsDesc: 'सीधे अपने डिवाइस पर अलर्ट प्राप्त करें।',
    emailUpdates: 'ईमेल अपडेट',
    emailUpdatesPrefDesc: 'साप्ताहिक सारांश और महत्वपूर्ण अलर्ट।',
    privacyAndData: 'गोपनीयता एवं डेटा',
    anonymousReporting: 'गुमनाम रिपोर्टिंग',
    anonymousReportingDesc: 'सार्वजनिक फ़ीड में अपना नाम छिपाएं।',
    shareLocationData: 'स्थान डेटा साझा करें',
    shareLocationDataDesc: 'नगर योजनाकारों को हॉटस्पॉट मैप करने में सहायता करें।',
    appPreferences: 'ऐप प्राथमिकताएं',
    theme: 'थीम (Theme)',
    systemDefaultDark: 'सिस्टम डिफ़ॉल्ट (डार्क)',
    highContrast: 'हाई कंट्रास्ट (High Contrast)',
    language: 'भाषा (Language)',
    dangerZone: 'डेंजर ज़ोन',
    deleteAccount: 'खाता हटाएं',
    deleteAccountWarning: 'अपने खाते और सभी रिपोर्ट इतिहास को स्थायी रूप से हटाएं। यह क्रिया वापस नहीं ली जा सकती।',
    saved: 'सहेजा गया!',
    supportTitle: 'सहायता एवं सहयोग',
    emergency: 'आपातकालीन सेवाएं',
    policeFireMedical: 'पुलिस / अग्निशमन / चिकित्सा',
    nonEmergencyPolice: 'गैर-आपातकालीन पुलिस',
    contactUs: 'हमसे संपर्क करें',
    emailSupport: 'ईमेल सहायता',
    liveChat: 'लाइव चैट',
    liveChatHours: 'उपलब्ध सुबह 9 बजे से शाम 5 बजे तक',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    sendFeedback: 'प्रतिक्रिया भेजें',
    sendFeedbackSubtitle: 'कोई तकनीकी समस्या मिली या सुझाव है? हमारी टीम को बताएं।',
    message: 'संदेश',
    describeIssuePlaceholder: 'अपनी समस्या या सुझाव विस्तार से लिखें...',
    submitFeedback: 'प्रतिक्रिया सबमिट करें',
    faq1Q: 'मैं अपनी दर्ज रिपोर्ट को कैसे ट्रैक करूँ?',
    faq1A: "साइडबार में 'मेरी ट्रैकिंग' विकल्प पर जाएं। वहां आपको अपनी सभी प्रस्तुत रिपोर्टें और उनकी वर्तमान स्थिति (लंबित, प्रगति पर, हल) दिखाई देंगी।",
    faq2Q: 'क्या मेरी पहचान सार्वजनिक की जाएगी?',
    faq2A: "नहीं। जब तक आप प्राथमिकताओं में अपनी सेटिंग्स नहीं बदलते, तब तक आपकी रिपोर्ट 'गुमनाम नागरिक' के रूप में दिखाई देती है।",
    faq3Q: 'गंभीर आपातकाल में मुझे क्या करना चाहिए?',
    faq3A: 'अर्बन आई केवल गैर-आपातकालीन बुनियादी ढांचे की रिपोर्टिंग के लिए है। जीवन या सुरक्षा के तात्कालिक खतरे में तुरंत राष्ट्रीय आपातकालीन सेवा 112/100 पर कॉल करें।',
    incidentInspection: 'समस्या का निरीक्षण',
    officialDispatch: 'आधिकारिक नगर निगम प्रेषण',
    deleteReport: 'रिपोर्ट हटाएं',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    generating: 'तैयार किया जा रहा है...',
    editFormalLetter: 'शिकायत पत्र संपादित करें',
    saveFormalLetter: 'पत्र सहेजें',
    resetOfficialTemplate: 'प्रारूप रीसेट करें',
    copyLetter: 'पत्र कॉपी करें',
    copied: 'कॉपी हो गया!',
    status: 'वर्तमान स्थिति',
    assignedDepartment: 'आवंटित विभाग',
    reportedBy: 'द्वारा रिपोर्ट किया गया',
    dateReported: 'रिपोर्ट तिथि',
    locationCoordinates: 'स्थान निर्देशांक',
    viewOnGoogleMaps: 'गूगल मैप्स पर देखें',
    verifiedReports: 'सत्यापित रिपोर्ट',
    incidentRecord: 'रिकॉर्ड',
    severityLevel: 'गंभीरता स्तर (SEVERITY)',
    incidentStatus: 'समस्या की स्थिति',
    verifiableDispatchSent: 'सत्यापनीय प्रेषण ईमेल भेजा गया',
    openEmailPreview: 'ईमेल पूर्वावलोकन खोलें',
    editLetterHelp: 'आप इस औपचारिक शिकायत पत्र के किसी भी हिस्से को संपादित कर सकते हैं या पीडीएफ डाउनलोड करने से पहले लैंडमार्क नोट जोड़ सकते हैं।',
    adminStatusTriage: 'प्रशासनिक स्थिति प्रबंधन (Status Triage)',
    markNew: 'नई (Mark New)',
    markAssigned: 'आवंटित (Mark Assigned)',
    markResolved: 'हल हुआ (सभी नागरिकों को सूचित करें)',
    closeInspector: 'निरीक्षक बंद करें',
    signInSubtitle: 'आगे बढ़ने के लिए अपने नागरिक पोर्टल में साइन इन करें।',
    emailLogin: 'ईमेल लॉगिन',
    phoneOtp: 'फ़ोन (OTP)',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    phoneNumber: 'फ़ोन नंबर',
    oneTimePassword: 'वन-टाइम पासवर्ड (OTP)',
    sendVerificationCode: 'सत्यापन कोड भेजें',
    verifyAndSignIn: 'सत्यापित करें और साइन इन करें',
    newToUrbanEye: 'अर्बन आई पर नए हैं?',
    createAccount: 'खाता बनाएं',
    officialAccess: 'अधिकारी लॉगिन (Official Access)',
    empoweringCitizens: 'सशक्त नागरिक।',
    improvingCities: 'उन्नत शहर।',
    joinThousands: 'शहरी समस्याओं की निगरानी और रीयल-टाइम रिपोर्टिंग करने वाले हजारों नागरिकों से जुड़ें।',
    secureConnection: 'सुरक्षित एवं एन्क्रिप्टेड कनेक्शन',
    citizenRegistration: 'नागरिक पंजीकरण',
    alreadyRegistered: 'क्या आपके पास पहले से खाता है?',
    viewAllAlerts: 'सभी सामुदायिक अलर्ट देखें →',
    pinsLive: 'पिन लाइव',
    myLocation: 'मेरा स्थान',
    radarOn: 'रडार चालू',
    radarOff: 'रडार बंद',
    showCards: 'कार्ड दिखाएं',
    fullMap: 'पूर्ण मानचित्र',
    feed: 'फ़ीड',
    liveIncidentFeed: 'लाइव घटना फ़ीड',
    noIncidentsForFilter: 'वर्तमान फ़िल्टर के लिए कोई घटना नहीं मिली।',
    myReportsAndPdf: 'मेरी रिपोर्ट्स और पीडीएफ',
    inspectIncidentDetails: 'घटना विवरण जांचें',
    clickMapToPin: 'पिन करने के लिए मानचित्र पर क्लिक करें',
    severityTitle: 'गंभीरता',
    allSeverities: 'सभी गंभीरताएं',
    highSeverity: 'उच्च गंभीरता',
    mediumSeverity: 'मध्यम गंभीरता',
    lowSeverity: 'कम गंभीरता',
    viewPins: 'पिन देखें',
    heatmap: 'हीटमैप',
    allIssues: 'सभी घटनाएं',
    confirmSignOutTitle: 'क्या आप वाकई साइन आउट करना चाहते हैं?',
    confirmSignOutDesc: 'क्या आप निश्चित रूप से अपना वर्तमान सत्र समाप्त करना चाहते हैं? अपने डैशबोर्ड और रिपोर्ट्स तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।',
    yesSignOut: 'हाँ, साइन आउट करें',
    noCancel: 'नहीं, रद्द करें',
    signOutSecurely: 'सुरक्षित साइन आउट',
    continueWithGoogle: 'गूगल के साथ जारी रखें',
    googleSignIn: 'गूगल से साइन इन करें',
    googleSignUp: 'गूगल से खाता बनाएं',
    orContinueWith: 'या इसके साथ जारी रखें',
    orRegisterWithEmail: 'या ईमेल से पंजीकरण करें',
    googleAuthSuccess: 'गूगल प्रमाणीकरण सफल रहा',
    googleAuthFailed: 'गूगल प्रमाणीकरण विफल रहा',
    verifyEmailTitle: 'अपने ईमेल को सत्यापित करें',
    verifyEmailSubtitle: 'हमने 6 अंकों का सत्यापन कोड भेजा है:',
    enterOtpCode: '6 अंकों का ओटीपी कोड दर्ज करें',
    verifyAndCreate: 'सत्यापित करें और खाता बनाएं',
    resendOtp: 'कोड पुनः भेजें',
    otpResent: 'सत्यापन कोड पुनः भेज दिया गया है!',
    invalidOtp: 'अमान्य या समाप्त हो चुका ओटीपी कोड। कृपया पुनः प्रयास करें।',
    verifyingOtp: 'सत्यापन किया जा रहा है...',
    didNotReceiveCode: 'कोड नहीं मिला?',
    resendIn: 'पुनः भेजें',
    allAlerts: 'सभी अलर्ट',
    criticalEmergency: 'अति आवश्यक / आपातकालीन',
    civicAdvisories: 'नागरिक परामर्श',
    serviceRestored: 'सेवा बहाल',
    publicNotices: 'सार्वजनिक सूचना',
    searchAlertsPlaceholder: 'कीवर्ड, वार्ड या विषय से अलर्ट खोजें...',
    listenAlert: 'सुने',
    listening: 'ऑडियो चल रहा है...',
    stopListening: 'रोकें',
    shareAlert: 'साझा करें',
    alertCopied: 'अलर्ट विवरण कॉपी हो गया!',
    staySafeAcknowledged: 'पुष्टि की गई',
    acknowledgedBy: 'नागरिकों ने पुष्टि की',
    affectedArea: 'प्रभावित क्षेत्र',
    emergencyHotline: 'आपातकालीन हेल्पलाइन',
    clearAllNotifs: 'सभी हटाएं',
    noNotifications: 'कोई नई नागरिक सूचना नहीं है',
    allCaughtUpDesc: 'आप सभी सामुदायिक सूचनाओं से पूरी तरह अपडेट हैं।'
  },
  mr: {
    appTitle: 'अर्बन आय (Urban EYE)',
    appSubtitle: 'स्मार्ट नागरी पायाभूत सुविधा ट्रॅकर',
    dashboard: 'डॅशबोर्ड',
    reportIssue: 'समस्या नोंदवा',
    newReport: 'नवीन तक्रार नोंदवा',
    myReports: 'माझे ट्रॅकिंग',
    liveMap: 'थेट शहर नकाशा',
    alerts: 'नागरी सूचना',
    activity: 'शहरातील घडामोडी',
    profile: 'नागरिक प्रोफाइल',
    settings: 'सेटिंग्ज',
    support: 'मदत व समर्थन',
    signOut: 'बाहेर पडा (Sign Out)',
    signIn: 'साइन इन करा',
    register: 'नागरिक नोंदणी',
    viewProfile: 'प्रोफाइल पहा',
    getStartedTour: "'सुरुवात करा' माहिती",
    privacyPolicy: 'गोपनीयता धोरण',
    accessibility: 'सुगम्यता पर्याय',
    liveFeed: 'थेट फीड',
    offline: 'ऑफलाइन',
    notifications: 'सूचना',
    markAllRead: 'सर्व वाचले म्हणून खूण करा',
    civicNotifications: 'नागरी अधिसूचना',
    recentAnnouncements: 'महापालिका घोषणा',
    searchPlaceholder: 'शहरातील समस्या, प्रभाग शोधा...',
    pothole: 'रस्त्यावरील खड्डा',
    garbage: 'कचरा ढीग / अस्वच्छता',
    waterLeak: 'पाणी गळती',
    streetlight: 'बंद पथदिवा',
    reported: 'नोंदवले',
    inProgress: 'काम प्रगतीपथावर',
    resolved: 'निवारण झाले',
    critical: 'अति गंभीर',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'सामान्य',
    verifiedCitizen: 'प्रमाणित नागरिक',
    municipalAdmin: 'महापालिका प्रशासक',
    welcomeBack: 'पुन्हा स्वागत आहे',
    citizen: 'नागरिक',
    selectLanguage: 'भाषा निवडा',
    themeToggled: 'थीम बदलली',
    coreAccess: 'मुख्य सेवा',
    cityNetwork: 'शहर नेटवर्क',
    account: 'खाते',
    reportedIssues: 'नोंदवलेल्या समस्या',
    analytics: 'विश्लेषण',
    users: 'वापरकर्ते',
    announcements: 'घोषणा',
    liveGridActive: 'थेट ग्रिड सक्रिय',
    dashboardSubtitle: 'थेट नागरी पाळत, सामुदायिक प्रभाव ट्रॅकिंग आणि नागरी समस्या निवारण व्यवस्था.',
    syncLive: 'थेट सिंक करा',
    syncing: 'सिंक होत आहे...',
    communityIssues: 'सामुदायिक समस्या',
    inArea: 'परिसरात',
    gpsVerified: 'GPS द्वारे सत्यापित',
    verifiedResolved: 'सत्यापित निवारण',
    civicFixes: 'सुधारणा',
    trustScore: 'नागरी विश्वास',
    civicKarma: 'नागरी कर्मा',
    resolutionRate: 'निवारण दर',
    citywide: 'संपूर्ण शहरात',
    mySubmissions: 'माझ्या नोंदी',
    filed: 'नोंदवले',
    done: 'पूर्ण',
    ptsToNextRank: 'गुण पुढील श्रेणीसाठी',
    reportIssueAction: 'समस्या नोंदवा',
    aiDetection: 'AI शोध',
    myActivity: 'माझे कामकाज',
    statusAndPdf: 'स्थिती व PDF',
    cityScanner: 'शहर स्कॅनर',
    emergencySOS: 'आपत्कालीन SOS',
    hotlines: 'हेल्पलाइन क्रमांक',
    communityMap: 'सामुदायिक नकाशा',
    pins: 'ठिकाणे',
    myGps: 'माझे GPS',
    locating: 'शोधत आहे...',
    reset: 'रीसेट करा',
    live: 'थेट',
    recentAreaActivity: 'आपल्या परिसरातील अलीकडील घडामोडी',
    tapIncidentHint: 'तपशील किंवा अधिकृत PDF साठी टॅप करा',
    active: 'सक्रिय',
    filterBy: 'फिल्टर:',
    all: 'सर्व',
    allCategories: 'सर्व श्रेणी',
    potholes: 'रस्त्यावरील खड्डे',
    wasteGarbage: 'कचरा / अस्वच्छता',
    waterLeaks: 'पाणी गळती',
    streetlights: 'पथदिवे',
    roadHazard: 'रस्त्यावरील खड्डा / अडथळा',
    illegalWaste: 'कचरा ढीग / अस्वच्छता',
    waterSewage: 'पाणी गळती / सांडपाणी',
    civicInfra: 'नागरी पायाभूत सुविधा',
    scanningGrid: 'सामुदायिक ग्रिड स्कॅन करत आहे...',
    ward: 'प्रभाग',
    confirmExistsTitle: 'या समस्येची खात्री करा',
    inspectPdf: 'पहा व PDF',
    noMatchingReports: 'आपल्या भागात कोणतीही तक्रार आढळली नाही.',
    clearFiltersHint: 'फिल्टर काढा किंवा रस्त्यावरील नवीन समस्या नोंदवा.',
    resetFilters: 'फिल्टर रीसेट करा',
    civicEngagementScore: 'नागरी सहभाग गुण',
    pointsShort: 'गुण',
    tierCitizen: 'श्रेणी नागरिक',
    levelProgress: 'पातळी प्रगती',
    ptsTo: 'गुण शिल्लक:',
    nextTier: 'पुढील पातळी',
    legend: 'लीजेंड',
    howToBoostScore: 'गुण कसे वाढवावेत:',
    verifiedIncidentReport: 'सत्यापित तक्रार नोंद',
    municipalFixCompleted: 'महापालिका काम पूर्ण',
    confirmCommunityHazard: 'धोकादायक समस्येची पुष्टी',
    activeAlerts: 'सक्रिय सूचना',
    alertsCount: 'सूचना',
    allClearSector: 'भागात सर्व सुरक्षित',
    allClearDesc: 'कोणतीही गंभीर सूचना किंवा रस्ता बंदी नाही.',
    proTipsTitle: 'जलद निवारणासाठी उपयुक्त टिप्स',
    tip1Title: 'मोठ्या कोनातून फोटो घ्या:',
    tip1Desc: 'रस्ता दुभाजक किंवा दुकाने फोटोमध्ये दाखवा जेणेकरून टीमला जागा शोधता येईल.',
    tip2Title: 'नकाशा पिन तपासा:',
    tip2Desc: 'घटनास्थळावरून दूर गेल्यावर नोंदवत असल्यास पिन अचूक ठिकाणी सेट करा.',
    tip3Title: 'अधिकृत PDF डाउनलोड करा:',
    tip3Desc: 'स्थानिक नगरसेवक किंवा सोसायटीसाठी तयार PDF वापरा.',
    emergencyModalTitle: 'नागरी आपत्कालीन मदत क्रमांक',
    emergencyModalSubtitle: 'तातडीच्या सेवांशी थेट संपर्क साधा',
    close: 'बंद करा',
    policeHelpline: 'राष्ट्रीय आणीबाणी / पोलीस',
    policeDesc: 'पोलीस, रुग्णवाहिका व आपत्ती नियंत्रण',
    fireHelpline: 'अग्निशामक नियंत्रण कक्ष',
    fireDesc: 'आग व बचाव कार्य',
    pwdHelpline: 'महापालिका / बांधकाम विभाग',
    pwdDesc: 'रस्ता खचणे, खड्डे व पडलेली झाडे',
    waterHelpline: 'पाणी पुरवठा व मुख्य पाइपलाइन',
    waterDesc: 'मोठी पाणी गळती व पूरस्थिती',
    electricityHelpline: 'विद्युत महामंडळ / उघडी तार',
    electricityDesc: 'उघड्या तारा व ट्रान्सफॉर्मर आग',
    ambassadorBadge: 'नागरी दूत',
    guardianBadge: 'सत्यापित रक्षक',
    activeBadge: 'सक्रिय नागरिक',
    contributorBadge: 'सामुदायिक योगदानकर्ता',
    platinumTier: 'प्लॅटिनम',
    goldTier: 'सुवर्ण (Gold)',
    silverTier: 'चांदी (Silver)',
    bronzeTier: 'कांस्य (Bronze)',
    mySubmittedReports: 'माझे सादर केलेले अहवाल',
    liveTracking: 'थेट ट्रॅकिंग',
    reportsSubtitle: 'आपण नोंदवलेल्या समस्यांची सद्यस्थिती थेट ट्रॅक करा',
    reportNewIssue: 'नवीन समस्या नोंदवा',
    allReports: 'सर्व अहवाल',
    noReportsFound: 'कोणतीही तक्रार आढळली नाही',
    noReportsSubmittedYet: 'आपण अद्याप कोणतीही समस्या नोंदवली नाही.',
    submitFirstReport: 'आपली पहिली तक्रार नोंदवा',
    viewCard: 'पहा',
    noImageCaptured: 'छायाचित्र उपलब्ध नाही',
    reportsCount: 'तक्रारी',
    reportSingle: 'तक्रार',
    emergencyServices: 'तातडीच्या सेवा',
    emergencyHelplines: 'महापालिका आपत्कालीन मदत क्रमांक',
    police: 'पोलीस नियंत्रण कक्ष',
    ambulance: 'रुग्णवाहिका व वैद्यकीय',
    fireDepartment: 'अग्निशामक व बचाव',
    municipalHelpline: 'आपत्ती व नागरी कक्ष',
    inspectDetails: 'तपशील पहा',
    confirmIssue: 'खात्री करा',
    confirmed: 'पुष्टी झाली',
    activeWatch: 'सक्रिय पाळत',
    citizenProfile: 'नागरिक प्रोफाइल',
    profileSubtitle: 'ओळख व्यवस्थापित करा, नागरी गुण ट्रॅक करा आणि इतिहास पहा',
    editProfile: 'प्रोफाइल संपादित करा',
    cancel: 'रद्द करा',
    saveChanges: 'बदल जतन करा',
    saving: 'जतन करत आहे...',
    profileUpdated: 'प्रोफाइल यशस्वीरित्या अद्यतनित झाली!',
    exportRecord: 'नोंदी निर्यात करा (JSON)',
    fullName: 'पूर्ण नाव',
    contactPhone: 'संपर्क फोन',
    wardNeighborhood: 'महानगरपालिका प्रभाग / परिसर',
    activeSince: 'सक्रियता दिनांक',
    civicStatement: 'नागरी संकल्पना / ध्येय',
    systemStatus: 'प्रणाली स्थिती',
    adminCommand: 'प्रशासक कमांड',
    civicTierRank: 'नागरी श्रेणी पद',
    tierMilestone: 'पुढील स्तर टप्पा',
    ptsToLevelUp: 'गुण स्तरवाढीसाठी',
    citizenPreferences: 'नागरिक प्राधान्ये',
    emailReportUpdates: 'ईमेल अहवाल सूचना',
    emailUpdatesDesc: 'पालिकेने समस्या सोडवल्यावर सूचना मिळवा',
    criticalSmsAlerts: 'महत्त्वाचे एसएमएस अलर्ट',
    smsAlertsDesc: 'रस्ता आणि पाणी साचण्याच्या गंभीर सूचना',
    locationAutoTag: 'स्थान स्वयं-टॅग',
    locationAutoTagDesc: 'फोटोवरून रस्त्याचे नाव स्वयंचलित भरा',
    totalReports: 'एकूण नोंदवलेल्या तक्रारी',
    submittedByYou: 'आपल्याकडून नोंदवलेल्या',
    fixRate: 'निवारण दर',
    trustScoreLabel: 'विश्वासार्हता गुण',
    reliabilityRating: 'नागरी विश्वासार्हता रेटिंग',
    endorsements: 'सामुदायिक समर्थन',
    communityConfirmations: 'नागरिक पुष्टीकरणे',
    civicAchievementsBadges: 'नागरी यश व पदके',
    unlocked: 'अनलॉक केले',
    myReportedIncidents: 'माझ्या नोंदवलेल्या तक्रारी',
    trackResolutionDesc: 'निवारण स्थिती ट्रॅक करा आणि अधिकृत पालिका पीडीएफ डाउनलोड करा',
    loadingCivicHistory: 'नागरी इतिहास लोड होत आहे...',
    noIncidentsFound: 'या निकषात कोणतीही तक्रार आढळली नाही.',
    foundHazardQuestion: 'आपल्या परिसरात खड्डा, दिवाबत्ती बिघाड किंवा पाणी गळती आढळली का?',
    reportAnIssue: 'समस्या नोंदवा',
    exploreLiveMap: 'थेट शहर नकाशा पहा',
    exploreMapDesc: 'थेट पिन आणि पालिका पथकांची माहिती पहा',
    submitRoadHazard: 'नवीन रस्त्याची समस्या नोंदवा',
    submitHazardDesc: 'त्वरित एआय वर्गीकरण, जिओलोकेशन आणि पाठवणी',
    firstResponder: 'प्रथम प्रतिसादकर्ता',
    firstResponderDesc: 'आपली पहिली पडताळलेली तक्रार नोंदवा',
    potholeHunter: 'खड्डे शोधक',
    potholeHunterDesc: '३ किंवा अधिक रस्त्यावरील खड्डे नोंदवा',
    wasteBuster: 'कचरा निर्मूलक',
    wasteBusterDesc: 'कचरा साचल्याची तक्रार नोंदवा',
    aquaSentinel: 'जल रक्षक',
    aquaSentinelDesc: 'जलवाहिनी गळती किंवा ड्रेनेज समस्या नोंदवा',
    nightWatch: 'रात्र पहारेकरी',
    nightWatchDesc: 'सुरक्षेसाठी बंद पडलेली दिवाबत्ती नोंदवा',
    civicPillar: 'नागरी आधारस्तंभ',
    civicPillarDesc: '९० किंवा अधिक विश्वासार्हता गुण मिळवा',
    intelligentIncidentReporting: 'स्मार्ट समस्या नोंदणी',
    reportPageSubtitle: 'फोटो काढा किंवा अपलोड करा. अर्बन आय स्वयंचलितपणे स्थान शोधेल, एआय द्वारे विश्लेषण करेल आणि थेट पालिका विभागाला कळवेल.',
    trackPastReports: 'मागील तक्रारी ट्रॅक करा',
    incidentDispatched: 'तक्रार यशस्वीरित्या पाठवली गेली!',
    incidentDispatchedDesc: 'पालिका प्राधिकरणाला त्वरित कारवाईसाठी कळवले आहे.',
    categoryLabel: 'श्रेणी (CATEGORY)',
    severityLabel: 'तीव्रता (SEVERITY)',
    assignedDept: 'नेमलेला विभाग',
    citizenReportsCount: 'नागरिक तक्रारी',
    generatedComplaintLetter: 'तयार केलेले अधिकृत पालिका तक्रार पत्र',
    editLetter: 'पत्र संपादित करा',
    saveUpdates: 'बदल जतन करा',
    downloadPdfReport: 'पीडीएफ अहवाल डाउनलोड करा',
    generatingPdf: 'पीडीएफ तयार होत आहे...',
    inspectAiDetails: 'एआय तपशील पहा',
    viewInMyReports: 'माझ्या ट्रॅकिंगमध्ये पहा',
    reportAnotherIncident: 'दुसरी समस्या नोंदवा',
    uploadEvidencePhoto: 'पुरावा फोटो अपलोड करा',
    changePhoto: 'फोटो बदला',
    takeNewPhoto: 'नवीन फोटो काढा',
    tapToSelectPhoto: 'फोटो निवडण्यासाठी किंवा काढण्यासाठी टॅप करा',
    gpsAutoExtraction: 'स्वयंचलित जीपीएस आणि फोटो कॉम्प्रेस सुविधा',
    browseFiles: 'फायली निवडा',
    takePhoto: 'फोटो काढा',
    selectDefectCategory: 'समस्येचा प्रकार निवडा',
    autoClassifiedHint: 'खात्री नसल्यास एआय स्वयंचलित ठरवेल',
    roadsAndWorks: 'रस्ते व बांधकाम विभाग',
    sanitation: 'स्वच्छता विभाग',
    waterSupply: 'पाणी पुरवठा विभाग',
    electricalDept: 'विद्युत विभाग',
    submitIncidentReport: 'तक्रार दाखल करा',
    runningAiTriage: 'एआय विश्लेषण व पाठवणी सुरू आहे...',
    submitNotice: 'तक्रार दाखल केल्यावर, एआय ५० मीटरमधील तक्रारी एकत्र करून अभियंत्यांकडे पाठवेल.',
    pinpointLocation: 'अचूक स्थान निवडा',
    dragPinHint: 'पिन ड्रॅग करा किंवा नकाशावर टॅप करून जागा निवडा',
    realtimeAddressSync: 'थेट पत्ता सिंक',
    detectedLandmark: 'शोधलेला परिसर आणि रस्त्याचा पत्ता',
    autoFilledFromPin: 'पिनवरून स्वयंचलित भरलेला',
    latitude: 'अक्षांश (Latitude)',
    longitude: 'रेखांश (Longitude)',
    cityActivityTitle: 'शहरातील घडामोडी',
    cityActivitySubtitle: 'नागरिक तक्रारी आणि पालिका कर्मचाऱ्यांच्या कामाचा थेट प्रवाह.',
    loadOlderActivity: 'मागील घडामोडी पहा ↓',
    todaysImpact: 'आजचा प्रभाव',
    newReportsStat: 'नवीन तक्रारी',
    issuesResolved: 'समस्या निवारण',
    activeCityCrews: 'सक्रिय पालिका पथके',
    anonymousCitizen: 'निनावी नागरिक',
    cityCrew: 'पालिका पथक',
    cityAdmin: 'शहर प्रशासक (Admin)',
    near: 'जवळ',
    justNow: 'आत्ताच',
    time45mAgo: '४५ मिनिटांपूर्वी',
    time2hAgo: '२ तासांपूर्वी',
    time3hAgo: '३ तासांपूर्वी',
    reportedRoadHazard: 'रस्त्यावरील खड्ड्याची तक्रार नोंदवली',
    resolvedStreetlightOutage: 'स्ट्रीटलाइट दुरुस्ती केली',
    reportedWaterLeak: 'पाणी गळतीची तक्रार नोंदवली',
    escalatedInfraIssue: 'पायाभूत सुविधेची तक्रार वर्ग केली',
    communityAlertsTitle: 'नागरी सूचना व अलर्ट',
    communityAlertsSubtitle: 'शहरातील तात्काळ सूचना आणि आपत्कालीन अपडेट्स मिळवा.',
    liveNetwork: 'थेट नेटवर्क',
    allCaughtUp: 'सर्व अद्यतने पूर्ण झाली आहेत',
    time10mAgo: '१० मिनिटांपूर्वी',
    time1dAgo: '१ दिवसापूर्वी',
    alert1Title: 'रस्ता बंद: मुख्य रस्ता (Main St.)',
    alert1Desc: 'तातडीच्या जलवाहिनी दुरुस्तीसाठी मेन स्ट्रीट बंद राहील. कृपया पर्यायी मार्गांचा वापर करा.',
    alert2Title: 'वीज पुरवठा सुरळीत',
    alert2Desc: 'नॉर्थसाइड भागात वीज पुरवठा पूर्ववत सुरू करण्यात आला आहे. सहकार्याबद्दल धन्यवाद.',
    alert3Title: 'नियोजित देखभाल कार्य',
    alert3Desc: 'या आठवड्याच्या शेवटी शहरातील उद्यानांमध्ये दुरुस्तीचे काम केले जाईल.',
    preferences: 'प्राधान्ये (Settings)',
    settingsSubtitle: 'आपले अर्बन आय खाते आणि सूचना व्यवस्थापित करा.',
    notificationsTitle: 'सूचना (Notifications)',
    pushNotifications: 'पुश सूचना (Push Notifications)',
    pushNotificationsDesc: 'थेट आपल्या डिव्हाइसवर सूचना मिळवा.',
    emailUpdates: 'ईमेल सूचना',
    emailUpdatesPrefDesc: 'साप्ताहिक आढावा आणि महत्त्वाचे अलर्ट.',
    privacyAndData: 'गोपनीयता आणि डेटा',
    anonymousReporting: 'निनावी तक्रार नोंदणी',
    anonymousReportingDesc: 'सार्वजनिक फीडमध्ये आपले नाव लपवा.',
    shareLocationData: 'स्थान माहिती शेअर करा',
    shareLocationDataDesc: 'समस्यांचे विश्लेषण करण्यासाठी मदत करा.',
    appPreferences: 'अ‍ॅप प्राधान्ये',
    theme: 'थीम (Theme)',
    systemDefaultDark: 'सिस्टम डीफॉल्ट (डार्क)',
    highContrast: 'हाय कॉन्ट्रास्ट (High Contrast)',
    language: 'भाषा (Language)',
    dangerZone: 'धोका क्षेत्र (Danger Zone)',
    deleteAccount: 'खाते हटवा',
    deleteAccountWarning: 'आपले खाते आणि सर्व तक्रारींचा इतिहास कायमचा हटवा. ही कृती पूर्ववत करता येत नाही.',
    saved: 'जतन झाले!',
    supportTitle: 'मदत व समर्थन',
    emergency: 'आपत्कालीन सेवा',
    policeFireMedical: 'पोलीस / अग्निशमन / वैद्यकीय',
    nonEmergencyPolice: 'गैर-आपत्कालीन पोलीस',
    contactUs: 'आमच्याशी संपर्क साधा',
    emailSupport: 'ईमेल समर्थन',
    liveChat: 'थेट चॅट',
    liveChatHours: 'सकाळी ९ ते संध्याकाळी ५ पर्यंत उपलब्ध',
    faqTitle: 'नेहमी विचारले जाणारे प्रश्न (FAQ)',
    sendFeedback: 'प्रतिक्रिया पाठवा',
    sendFeedbackSubtitle: 'काही अडचण किंवा सूचना आहे का? आमच्या टीमला कळवा.',
    message: 'संदेश',
    describeIssuePlaceholder: 'आपली अडचण किंवा सूचना येथे लिहा...',
    submitFeedback: 'प्रतिक्रिया पाठवा',
    faq1Q: 'मी नोंदवलेली तक्रार कशी ट्रॅक करावी?',
    faq1A: "साइडबारमधील 'माझे ट्रॅकिंग' विभागावर जा. तिथे आपल्याला तक्रारींची सध्याची स्थिती (प्रलंबित, सुरू किंवा पूर्ण) दिसेल.",
    faq2Q: 'माझी ओळख लोकांसाठी जाहीर होईल का?',
    faq2A: "नाही. आपण प्राधान्य बदलत नाही तोपर्यंत आपल्या तक्रारी 'निनावी नागरिक' म्हणून दिसतात.",
    faq3Q: 'गंभीर आणीबाणीत मी काय करावे?',
    faq3A: 'अर्बन आय केवळ पायाभूत सुविधांच्या तक्रारींसाठी आहे. जिवाला धोका असल्यास त्वरित ११२ वर कॉल करा.',
    incidentInspection: 'तक्रार तपासणी',
    officialDispatch: 'अधिकृत पालिका पाठवणी',
    deleteReport: 'तक्रार हटवा',
    downloadPdf: 'पीडीएफ डाउनलोड करा',
    generating: 'तयार होत आहे...',
    editFormalLetter: 'तक्रार पत्र संपादित करा',
    saveFormalLetter: 'पत्र जतन करा',
    resetOfficialTemplate: 'प्रारूप पूर्ववत करा',
    copyLetter: 'पत्र कॉपी करा',
    copied: 'कॉपी झाले!',
    status: 'सद्यस्थिती',
    assignedDepartment: 'नेमलेला विभाग',
    reportedBy: 'तक्रारदार',
    dateReported: 'तक्रार तारीख',
    locationCoordinates: 'स्थान निर्देशक',
    viewOnGoogleMaps: 'गुगल मॅपवर पहा',
    verifiedReports: 'सत्यापित तक्रारी',
    incidentRecord: 'नोंद',
    severityLevel: 'गंभीरता पातळी',
    incidentStatus: 'तक्रारीची स्थिती',
    verifiableDispatchSent: 'सत्यापनीय ईमेल पाठवले गेले',
    openEmailPreview: 'ईमेल पूर्वावलोकन पहा',
    editLetterHelp: 'आपण या औपचारिक तक्रार पत्रात बदल करू शकता किंवा पीडीएफ डाउनलोड करण्यापूर्वी परिसराची माहिती जोडू शकता.',
    adminStatusTriage: 'प्रशासकीय स्थिती व्यवस्थापन',
    markNew: 'नवीन (Mark New)',
    markAssigned: 'नियुक्त (Mark Assigned)',
    markResolved: 'निवारण झाले (सर्व नागरिकांना सूचित करा)',
    closeInspector: 'बंद करा',
    signInSubtitle: 'पुढे जाण्यासाठी आपल्या नागरिक खात्यामध्ये साइन इन करा.',
    emailLogin: 'ईमेल लॉगिन',
    phoneOtp: 'फोन (OTP)',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    phoneNumber: 'फोन नंबर',
    oneTimePassword: 'वन-टाइम पासवर्ड (OTP)',
    sendVerificationCode: 'पडताळणी कोड पाठवा',
    verifyAndSignIn: 'पडताळणी करून साइन इन करा',
    newToUrbanEye: 'अर्बन आयवर नवीन आहात?',
    createAccount: 'खाते तयार करा',
    officialAccess: 'अधिकारी प्रवेश (Official Access)',
    empoweringCitizens: 'सक्षम नागरिक.',
    improvingCities: 'प्रगत शहरे.',
    joinThousands: 'शहरी समस्यांची नोंद करणाऱ्या हजारो नागरिकांमध्ये सामील व्हा.',
    secureConnection: 'सुरक्षित आणि एन्क्रिप्टेड कनेक्शन',
    citizenRegistration: 'नागरिक नोंदणी',
    alreadyRegistered: 'आधीच खाते आहे का?',
    viewAllAlerts: 'सर्व नागरी सूचना पहा →',
    pinsLive: 'पिन थेट',
    myLocation: 'माझे स्थान',
    radarOn: 'रडार चालू',
    radarOff: 'रडार बंद',
    showCards: 'कार्ड दाखवा',
    fullMap: 'पूर्ण नकाशा',
    feed: 'फीड',
    liveIncidentFeed: 'थेट घटना फीड',
    noIncidentsForFilter: 'सध्याच्या फिल्टरसाठी कोणतीही घटना आढळली नाही.',
    myReportsAndPdf: 'माझे अहवाल आणि पीडीएफ',
    inspectIncidentDetails: 'घटना तपशील तपासा',
    clickMapToPin: 'पिन करण्यासाठी नकाशावर क्लिक करा',
    severityTitle: 'तीव्रता',
    allSeverities: 'सर्व तीव्रता',
    highSeverity: 'उच्च तीव्रता',
    mediumSeverity: 'मध्यम तीव्रता',
    lowSeverity: 'कमी तीव्रता',
    viewPins: 'पिन पहा',
    heatmap: 'हीटमॅप',
    allIssues: 'सर्व घटना',
    confirmSignOutTitle: 'तुम्हाला खरोखर साइन आउट करायचे आहे का?',
    confirmSignOutDesc: 'तुम्हाला तुमचे वर्तमान सत्र समाप्त करायचे आहे का? तुमच्या डॅशबोर्डवर प्रवेश करण्यासाठी तुम्हाला पुन्हा साइन इन करावे लागेल.',
    yesSignOut: 'होय, साइन आउट करा',
    noCancel: 'नाही, रद्द करा',
    signOutSecurely: 'सुरक्षितपणे बाहेर पडा',
    continueWithGoogle: 'गुगलसह पुढे जा',
    googleSignIn: 'गुगलने साइन इन करा',
    googleSignUp: 'गुगलने खाते तयार करा',
    orContinueWith: 'किंवा यासह पुढे जा',
    orRegisterWithEmail: 'किंवा ईमेलने नोंदणी करा',
    googleAuthSuccess: 'गुगल प्रमाणीकरण यशस्वी',
    googleAuthFailed: 'गुगल प्रमाणीकरण अयशस्वी',
    verifyEmailTitle: 'तुमचा ईमेल सत्यापित करा',
    verifyEmailSubtitle: 'आम्ही 6-अंकी पडताळणी कोड पाठवला आहे:',
    enterOtpCode: '6-अंकी OTP कोड टाका',
    verifyAndCreate: 'पडताळणी करा आणि खाते तयार करा',
    resendOtp: 'कोड पुन्हा पाठवा',
    otpResent: 'पडताळणी कोड यशस्वीरित्या पुन्हा पाठवला!',
    invalidOtp: 'अवैध किंवा कालबाह्य OTP कोड. कृपया तपासा आणि पुन्हा प्रयत्न करा.',
    verifyingOtp: 'पडताळणी करत आहे...',
    didNotReceiveCode: 'कोड मिळाला नाही का?',
    resendIn: 'पुन्हा पाठवा'
  },
  ta: {
    appTitle: 'அர்பன் ஐ (Urban EYE)',
    appSubtitle: 'ஸ்மார்ட் குடிமக்கள் உள்கட்டமைப்பு டிராக்கர்',
    dashboard: 'டாஷ்போர்டு',
    reportIssue: 'சிக்கலைப் புகாரளிக்கவும்',
    newReport: 'புதிய அறிக்கை',
    myReports: 'எனது கண்காணிப்பு',
    liveMap: 'நேரலை வரைபடம்',
    alerts: 'சமூக எச்சரிக்கைகள்',
    activity: 'நகர செயல்பாடுகள்',
    profile: 'குடிமக்கள் சுயவிவரம்',
    settings: 'அமைப்புகள்',
    support: 'உதவி & ஆதரவு',
    signOut: 'வெளியேறு (Sign Out)',
    signIn: 'உள்நுழைக',
    register: 'குடிமக்கள் பதிவு',
    viewProfile: 'சுயவிவரத்தைக் காண்க',
    getStartedTour: "'தொடங்குதல்' சுற்றுப்பயணம்",
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    accessibility: 'அணுகல்தன்மை',
    liveFeed: 'நேரலை ஊட்டம்',
    offline: 'ஆஃப்லைன்',
    notifications: 'அறிவிப்புகள்',
    markAllRead: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    civicNotifications: 'குடிமை அறிவிப்புகள்',
    recentAnnouncements: 'மாநகராட்சி அறிவிப்புகள்',
    searchPlaceholder: 'சிக்கல்கள், வார்டுகளைத் தேடுங்கள்...',
    pothole: 'சாலைக் குழி',
    garbage: 'குப்பை தேக்கம்',
    waterLeak: 'குடிநீர் குழாய் கசிவு',
    streetlight: 'பழுதடைந்த தெருவிளக்கு',
    reported: 'பதிவு செய்யப்பட்டது',
    inProgress: 'செயலில் உள்ளது',
    resolved: 'தீர்க்கப்பட்டது',
    critical: 'முக்கியமானது',
    high: 'உயர்',
    medium: 'நடுத்தர',
    low: 'குறைந்த',
    verifiedCitizen: 'சரிபார்க்கப்பட்ட குடிமகன்',
    municipalAdmin: 'மாநகராட்சி நிர்வாகி',
    welcomeBack: 'மீண்டும் வருக',
    citizen: 'குடிமகன்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    themeToggled: 'தீம் மாற்றப்பட்டது',
    coreAccess: 'முதன்மை சேவைகள்',
    cityNetwork: 'நகர நெட்வொர்க்',
    account: 'கணக்கு',
    reportedIssues: 'புகாரளிக்கப்பட்ட சிக்கல்கள்',
    analytics: 'பகுப்பாய்வு',
    users: 'பயனர்கள்',
    announcements: 'அறிவிப்புகள்',
    liveGridActive: 'நேரலை கட்டம் செயலில் உள்ளது',
    dashboardSubtitle: 'நிகழ்நேர நகர கண்காணிப்பு, சமூக தாக்க கண்காணிப்பு மற்றும் குடிமைத் தீர்வு அனுப்புதல்.',
    syncLive: 'நேரலை ஒத்திசைவு',
    syncing: 'ஒத்திசைக்கிறது...',
    communityIssues: 'சமூகப் பிரச்சினைகள்',
    inArea: 'பகுதியில்',
    gpsVerified: 'GPS மூலம் சரிபார்க்கப்பட்டது',
    verifiedResolved: 'சரிபார்க்கப்பட்டு தீர்க்கப்பட்டது',
    civicFixes: 'திருத்தங்கள்',
    trustScore: 'குடிமை நம்பிக்கை',
    civicKarma: 'குடிமை கர்மா',
    resolutionRate: 'தீர்வு விகிதம்',
    citywide: 'நகரமெங்கும்',
    mySubmissions: 'எனது பதிவுகள்',
    filed: 'தாக்கல்',
    done: 'முடிந்தது',
    ptsToNextRank: 'அடுத்த நிலைக்கு புள்ளிகள்',
    reportIssueAction: 'சிக்கலைப் புகாரளிக்கவும்',
    aiDetection: 'AI கண்டறிதல்',
    myActivity: 'எனது செயல்பாடு',
    statusAndPdf: 'நிலை & PDF',
    cityScanner: 'நகர ஸ்கேனர்',
    emergencySOS: 'அவசர SOS',
    hotlines: 'உதவி எண்கள்',
    communityMap: 'சமூக வரைபடம்',
    pins: 'இடங்கள்',
    myGps: 'எனது GPS',
    locating: 'கண்டறியப்படுகிறது...',
    reset: 'மீட்டமை',
    live: 'நேரலை',
    recentAreaActivity: 'உங்கள் பகுதியில் சமீபத்திய செயல்பாடுகள்',
    tapIncidentHint: 'விவரங்கள் அல்லது PDF-க்கு கிளிக் செய்யவும்',
    active: 'செயலில்',
    filterBy: 'வடிகட்டுக:',
    all: 'அனைத்தும்',
    allCategories: 'அனைத்து பிரிவுகளும்',
    potholes: 'சாலை குழிகள்',
    wasteGarbage: 'குப்பை தேக்கம்',
    waterLeaks: 'குடிநீர் கசிவு',
    streetlights: 'தெருவிளக்குகள்',
    roadHazard: 'சாலைக் குழி / ஆபத்து',
    illegalWaste: 'சட்டவிரோத குப்பை தேக்கம்',
    waterSewage: 'குடிநீர் கசிவு / கழிவுநீர்',
    civicInfra: 'குடிமை உள்கட்டமைப்பு',
    scanningGrid: 'சமூக கட்டமைப்பு ஸ்கேன் செய்யப்படுகிறது...',
    ward: 'வார்டு',
    confirmExistsTitle: 'சிக்கல் உள்ளதை உறுதிசெய்க',
    inspectPdf: 'பார் & PDF',
    noMatchingReports: 'பொருந்தக்கூடிய அறிக்கைகள் எதுவும் இல்லை.',
    clearFiltersHint: 'வடிகட்டிகளை மீட்டமைக்கவும் அல்லது புதிய சிக்கலைப் புகாரளிக்கவும்.',
    resetFilters: 'வடிகட்டிகளை மீட்டமை',
    civicEngagementScore: 'குடிமை ஈடுபாடு மதிப்பெண்',
    pointsShort: 'புள்ளிகள்',
    tierCitizen: 'நிலை குடிமகன்',
    levelProgress: 'நிலை முன்னேற்றம்',
    ptsTo: 'புள்ளிகள்:',
    nextTier: 'அடுத்த நிலை',
    legend: 'லெஜண்ட்',
    howToBoostScore: 'மதிப்பெண்ணை எவ்வாறு அதிகரிப்பது:',
    verifiedIncidentReport: 'சரிபார்க்கப்பட்ட அறிக்கை',
    municipalFixCompleted: 'நகராட்சி தீர்வு முடிந்தது',
    confirmCommunityHazard: 'ஆபத்தை உறுதிசெய்தல்',
    activeAlerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    alertsCount: 'எச்சரிக்கைகள்',
    allClearSector: 'பகுதியில் அனைத்தும் சரி',
    allClearDesc: 'முக்கியமான எச்சரிக்கைகள் அல்லது சாலை மூடல்கள் இல்லை.',
    proTipsTitle: 'விரைவான தீர்வுக்கு குறிப்புகள்',
    tip1Title: 'பரந்த கோணத்தில் படம் எடுக்கவும்:',
    tip1Desc: 'சாலை பிரிப்பான்கள் அல்லது கடைகளை புகைப்படத்தில் சேர்க்கவும்.',
    tip2Title: 'வரைபட பின்னை சரிபார்க்கவும்:',
    tip2Desc: 'சம்பவ இடத்தை விட்டுச் சென்ற பிறகு பதிவு செய்தால் வரைபட பின்னை மாற்றவும்.',
    tip3Title: 'அதிகாரப்பூர்வ PDF-ஐ பதிவிறக்கவும்:',
    tip3Desc: 'வார்டு உறுப்பினருக்கு அனுப்ப இந்த PDF அறிக்கையைப் பயன்படுத்தவும்.',
    emergencyModalTitle: 'அவசர உதவி எண்கள்',
    emergencyModalSubtitle: 'அவசர சேவைகளுக்கான நேரடி எண்கள்',
    close: 'மூடு',
    policeHelpline: 'தேசிய அவசரநிலை / காவல்துறை',
    policeDesc: 'காவல்துறை, ஆம்புலன்ஸ் & பேரிடர் கட்டுப்பாடு',
    fireHelpline: 'தீயணைப்பு கட்டுப்பாட்டு அறை',
    fireDesc: 'தீ விபத்து & மீட்பு பணிகள்',
    pwdHelpline: 'மாநகராட்சி / நெடுஞ்சாலை துறை',
    pwdDesc: 'சாலை சேதங்கள் & விழுந்த மரங்கள்',
    waterHelpline: 'குடிநீர் விநியோகம் & முக்கிய குழாய்',
    waterDesc: 'குழாய் உடைப்பு & வெள்ளம்',
    electricityHelpline: 'மின்சார வாரியம் / அறுந்த கம்பி',
    electricityDesc: 'மின்னழுத்த கம்பி & டிரான்ஸ்பார்மர் தீ',
    ambassadorBadge: 'குடிமை தூதர்',
    guardianBadge: 'சரிபார்க்கப்பட்ட பாதுகாவலர்',
    activeBadge: 'செயலில் உள்ள குடிமகன்',
    contributorBadge: 'சமூக பங்களிப்பாளர்',
    platinumTier: 'பிளாட்டினம்',
    goldTier: 'தங்கம் (Gold)',
    silverTier: 'வெள்ளி (Silver)',
    bronzeTier: 'வெண்கலம் (Bronze)',
    mySubmittedReports: 'எனது சமர்ப்பிக்கப்பட்ட அறிக்கைகள்',
    liveTracking: 'நேரலை கண்காணிப்பு',
    reportsSubtitle: 'நீங்கள் புகாரளித்த சிக்கல்களின் நேரலை நிலையை கண்காணிக்கவும்',
    reportNewIssue: 'புதிய புகாரைப் பதிவுசெய்க',
    allReports: 'அனைத்து அறிக்கைகளும்',
    noReportsFound: 'அறிக்கைகள் எதுவும் இல்லை',
    noReportsSubmittedYet: 'நீங்கள் இதுவரை எந்த உள்கட்டமைப்பு புகாரையும் அளிக்கவில்லை.',
    submitFirstReport: 'உங்கள் முதல் புகாரைப் பதிவுசெய்க',
    viewCard: 'பார்',
    noImageCaptured: 'படம் எதுவும் கிடைக்கவில்லை',
    reportsCount: 'அறிக்கைகள்',
    reportSingle: 'அறிக்கை',
    emergencyServices: 'அவசர சேவைகள்',
    emergencyHelplines: 'மாநகராட்சி அவசர உதவி எண்கள்',
    police: 'காவல்துறை கட்டுப்பாட்டு அறை',
    ambulance: 'ஆம்புலன்ஸ் & மருத்துவம்',
    fireDepartment: 'தீயணைப்பு & மீட்பு',
    municipalHelpline: 'பேரிடர் மேலாண்மை பிரிவு',
    inspectDetails: 'விவரங்களைக் காண்க',
    confirmIssue: 'உறுதிசெய்க',
    confirmed: 'உறுதிப்படுத்தப்பட்டது',
    activeWatch: 'செயலில் உள்ள கண்காணிப்பு',
    citizenProfile: 'குடிமக்கள் சுயவிவரம்',
    profileSubtitle: 'அடையாளத்தை நிர்வகிக்கவும், மதிப்பெண்ணைக் கண்காணிக்கவும், வரலாற்றைக் காணவும்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    cancel: 'ரத்து செய்',
    saveChanges: 'மாற்றங்களைச் சேமி',
    saving: 'சேமிக்கிறது...',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    exportRecord: 'பதிவை ஏற்றுமதி செய் (JSON)',
    fullName: 'முழுப் பெயர்',
    contactPhone: 'தொடர்பு தொலைபேசி',
    wardNeighborhood: 'மாநகராட்சி வார்டு / பகுதி',
    activeSince: 'செயலில் உள்ள காலம்',
    civicStatement: 'குடிமக்கள் பிரகடனம்',
    systemStatus: 'கணினி நிலை',
    adminCommand: 'நிர்வாகக் கட்டளை',
    civicTierRank: 'குடிமக்கள் அடுக்கு நிலை',
    tierMilestone: 'அடுத்த நிலை இலக்கு',
    ptsToLevelUp: 'புள்ளிகள் தேவை',
    citizenPreferences: 'குடிமக்கள் விருப்பங்கள்',
    emailReportUpdates: 'மின்னஞ்சல் அறிக்கை புதுப்பிப்புகள்',
    emailUpdatesDesc: 'சிக்கல் தீர்க்கப்படும்போது எச்சரிக்கைகள்',
    criticalSmsAlerts: 'முக்கியமான எஸ்எம்எஸ் எச்சரிக்கைகள்',
    smsAlertsDesc: 'அதிமுக்கிய சாலை மற்றும் வெள்ள அபாய எச்சரிக்கைகள்',
    locationAutoTag: 'இருப்பிட தானியங்கி குறிச்சொல்',
    locationAutoTagDesc: 'புகைப்படம் பதிவேற்றும்போது தெருப் பெயர் தானாக நிரப்பப்படும்',
    totalReports: 'மொத்த புகார்கள்',
    submittedByYou: 'உங்களால் சமர்ப்பிக்கப்பட்டது',
    fixRate: 'தீர்வு விகிதம்',
    trustScoreLabel: 'நம்பகத்தன்மை மதிப்பெண்',
    reliabilityRating: 'நம்பகத்தன்மை மதிப்பீடு',
    endorsements: 'சமூக உறுதிப்படுத்தல்கள்',
    communityConfirmations: 'குடிமக்கள் உறுதிப்படுத்தல்கள்',
    civicAchievementsBadges: 'குடிமக்கள் சாதனைகள் & பதக்கங்கள்',
    unlocked: 'திறக்கப்பட்டது',
    myReportedIncidents: 'எனது புகாரளிக்கப்பட்ட சம்பவங்கள்',
    trackResolutionDesc: 'தீர்வு நிலையைக் கண்காணித்து அதிகாரப்பூர்வ பிடிஎஃப் பதிவிறக்கவும்',
    loadingCivicHistory: 'குடிமக்கள் வரலாறு ஏற்றப்படுகிறது...',
    noIncidentsFound: 'இந்த வடிப்பானில் எந்த அறிக்கையும் இல்லை.',
    foundHazardQuestion: 'உங்கள் பகுதியில் பள்ளம், தெருவிளக்கு பழுது அல்லது நீர் கசிவு கண்டீர்களா?',
    reportAnIssue: 'சிக்கலைப் புகாரளிக்கவும்',
    exploreLiveMap: 'நேரலை வரைபடத்தை ஆராயுங்கள்',
    exploreMapDesc: 'நேரலை பின்கள் மற்றும் மாநகராட்சி குழுக்களைக் காண்க',
    submitRoadHazard: 'புதிய சாலை ஆபத்தைப் புகாரளிக்கவும்',
    submitHazardDesc: 'உடனடி ஏஐ வகைப்பாடு, இருப்பிடம் மற்றும் பணி ஆணை',
    firstResponder: 'முதல் பதிலளிப்பவர்',
    firstResponderDesc: 'உங்கள் முதல் சரிபார்க்கப்பட்ட புகாரை சமர்ப்பிக்கவும்',
    potholeHunter: 'குழி வேட்டைக்காரர்',
    potholeHunterDesc: '3 அல்லது அதற்கு மேற்பட்ட சாலைக் குழிகளைப் புகாரளிக்கவும்',
    wasteBuster: 'குப்பை ஒழிப்பாளர்',
    wasteBusterDesc: 'சட்டவிரோத குப்பை கொட்டலைப் புகாரளிக்கவும்',
    aquaSentinel: 'நீர் பாதுகாவலர்',
    aquaSentinelDesc: 'குடிநீர் குழாய் கசிவு அல்லது கழிவுநீர் கசிவைப் புகாரளிக்கவும்',
    nightWatch: 'இரவுக் காவலர்',
    nightWatchDesc: 'பாதுகாப்பிற்காக பழுதடைந்த தெருவிளக்கைப் புகாரளிக்கவும்',
    civicPillar: 'குடிமக்கள் தூண்',
    civicPillarDesc: '90 அல்லது அதற்கு மேற்பட்ட நம்பகத்தன்மை மதிப்பெண்ணைப் பெறுங்கள்',
    intelligentIncidentReporting: 'அறிவார்ந்த சம்பவ அறிக்கை',
    reportPageSubtitle: 'புகைப்படம் எடுக்கவும் அல்லது பதிவேற்றவும். அர்பன் ஐ தானாகவே இருப்பிடத்தைக் கண்டறிந்து, ஏஐ மூலம் பகுப்பாய்வு செய்து மாநகராட்சிக்கு அனுப்பும்.',
    trackPastReports: 'முந்தைய புகார்களைக் கண்காணிக்கவும்',
    incidentDispatched: 'புகார் வெற்றிகரமாக அனுப்பப்பட்டது!',
    incidentDispatchedDesc: 'மாநகராட்சி அதிகாரிக்கு அதிக முன்னுரிமையுடன் அறிவிக்கப்பட்டுள்ளது.',
    categoryLabel: 'வகை (CATEGORY)',
    severityLabel: 'தீவிரம் (SEVERITY)',
    assignedDept: 'ஒதுக்கப்பட்ட துறை',
    citizenReportsCount: 'குடிமக்கள் புகார்கள்',
    generatedComplaintLetter: 'உருவாக்கப்பட்ட அதிகாரப்பூர்வ மாநகராட்சி புகார் கடிதம்',
    editLetter: 'கடிதத்தைத் திருத்து',
    saveUpdates: 'புதுப்பிப்புகளைச் சேமி',
    downloadPdfReport: 'பிடிஎஃப் அறிக்கையைப் பதிவிறக்கு',
    generatingPdf: 'பிடிஎஃப் உருவாக்கப்படுகிறது...',
    inspectAiDetails: 'ஏஐ விவரங்களை ஆய்வு செய்',
    viewInMyReports: 'எனது கண்காணிப்பில் காண்க',
    reportAnotherIncident: 'மற்றொரு சிக்கலைப் புகாரளிக்கவும்',
    uploadEvidencePhoto: 'ஆதார புகைப்படத்தைப் பதிவேற்றவும்',
    changePhoto: 'புகைப்படத்தை மாற்று',
    takeNewPhoto: 'புதிய படம் எடுக்கவும்',
    tapToSelectPhoto: 'புகைப்படத்தைத் தேர்ந்தெடுக்க அல்லது எடுக்க தட்டவும்',
    gpsAutoExtraction: 'தானியங்கி ஜிபிஎஸ் மற்றும் சுருக்க அம்சம் இயக்கப்பட்டது',
    browseFiles: 'கோப்புகளைத் தேர்ந்தெடுக்கவும்',
    takePhoto: 'படம் எடுக்கவும்',
    selectDefectCategory: 'குறைபாட்டின் வகையைத் தேர்ந்தெடுக்கவும்',
    autoClassifiedHint: 'தெரியவில்லை என்றால் ஏஐ தானாக வகைப்படுத்தும்',
    roadsAndWorks: 'சாலைகள் & பணிகள் துறை',
    sanitation: 'துப்புரவுத் துறை',
    waterSupply: 'குடிநீர் வழங்கல் துறை',
    electricalDept: 'மின்சாரத் துறை',
    submitIncidentReport: 'புகாரைச் சமர்ப்பிக்கவும்',
    runningAiTriage: 'ஏஐ பகுப்பாய்வு மற்றும் அனுப்புதல் நடைபெறுகிறது...',
    submitNotice: 'சமர்ப்பித்தவுடன், நகல்களைத் தவிர்க்க ஏஐ 50மீ சுற்றளவிலுள்ள அறிக்கைகளை இணைத்து அதிகாரிகளுக்கு அனுப்பும்.',
    pinpointLocation: 'சரியான இருப்பிடத்தைக் குறிக்கவும்',
    dragPinHint: 'பினை நகர்த்தவும் அல்லது வரைபடத்தில் தட்டவும்',
    realtimeAddressSync: 'நேரலை முகவரி ஒத்திசைவு',
    detectedLandmark: 'கண்டறியப்பட்ட அடையாளம் மற்றும் தெரு முகவரி',
    autoFilledFromPin: 'பின்னிலிருந்து தானாக நிரப்பப்பட்டது',
    latitude: 'அட்சரேகை (Latitude)',
    longitude: 'தீர்க்கரேகை (Longitude)',
    cityActivityTitle: 'நகர செயல்பாடுகள்',
    cityActivitySubtitle: 'குடிமக்கள் புகார்கள் மற்றும் மாநகராட்சி குழுக்களின் நேரலை ஊட்டம்.',
    loadOlderActivity: 'பழைய செயல்பாடுகளைக் காண்க ↓',
    todaysImpact: 'இன்றைய தாக்கம்',
    newReportsStat: 'புதிய புகார்கள்',
    issuesResolved: 'தீர்க்கப்பட்ட சிக்கல்கள்',
    activeCityCrews: 'செயலில் உள்ள மாநகராட்சி குழுக்கள்',
    anonymousCitizen: 'பெயரற்ற குடிமகன்',
    cityCrew: 'மாநகராட்சி குழு',
    cityAdmin: 'நகர நிர்வாகி',
    near: 'அருகில்',
    justNow: 'சற்று முன்',
    time45mAgo: '45 நிமிடங்களுக்கு முன்',
    time2hAgo: '2 மணி நேரத்திற்கு முன்',
    time3hAgo: '3 மணி நேரத்திற்கு முன்',
    reportedRoadHazard: 'சாலை ஆபத்தை பதிவு செய்தார்',
    resolvedStreetlightOutage: 'தெருவிளக்கு பழுதுநீக்கினர்',
    reportedWaterLeak: 'நீர் கசிவை பதிவு செய்தார்',
    escalatedInfraIssue: 'உள்கட்டமைப்பு சிக்கலை முன்னெடுத்தார்',
    communityAlertsTitle: 'சமூக எச்சரிக்கைகள்',
    communityAlertsSubtitle: 'நேரலை நகர அறிவிப்புகள் மற்றும் அவசர தகவல்களை உடனுக்குடன் பெறவும்.',
    liveNetwork: 'நேரலை நெட்வொர்க்',
    allCaughtUp: 'நீங்கள் அனைத்தும் பார்த்துவிட்டீர்கள்',
    time10mAgo: '10 நிமிடங்களுக்கு முன்',
    time1dAgo: '1 நாளுக்கு முன்',
    alert1Title: 'முக்கிய சாலை மூடல்: மெயின் செயின்ட்',
    alert1Desc: 'குடிநீர் குழாய் பழுதுபார்ப்பு காரணமாக பிரதான சாலை மூடப்படும். மாற்றுப் பாதையைப் பயன்படுத்தவும்.',
    alert2Title: 'மின் தடை சரிசெய்யப்பட்டது',
    alert2Desc: 'நார்த்சைடு பகுதியில் மின்சாரம் முழுமையாக மீட்டெடுக்கப்பட்டுள்ளது. உங்கள் பொறுமைக்கு நன்றி.',
    alert3Title: 'திட்டமிடப்பட்ட பராமரிப்பு',
    alert3Desc: 'இந்த வார இறுதியில் பூங்காக்களில் பராமரிப்புப் பணிகள் நடைபெறும்.',
    preferences: 'விருப்பத்தேர்வுகள் (Settings)',
    settingsSubtitle: 'உங்கள் அர்பன் ஐ கணக்கு அமைப்புகள் மற்றும் அறிவிப்புகளை நிர்வகிக்கவும்.',
    notificationsTitle: 'அறிவிப்புகள் (Notifications)',
    pushNotifications: 'புஷ் அறிவிப்புகள் (Push Notifications)',
    pushNotificationsDesc: 'உங்கள் சாதனத்தில் நேரடியாக எச்சரிக்கைகளைப் பெறுங்கள்.',
    emailUpdates: 'மின்னஞ்சல் புதுப்பிப்புகள்',
    emailUpdatesPrefDesc: 'வாராந்திர சுருக்கங்கள் மற்றும் முக்கியமான எச்சரிக்கைகள்.',
    privacyAndData: 'தனியுரிமை & தரவு',
    anonymousReporting: 'பெயரற்ற அறிக்கை',
    anonymousReportingDesc: 'பொது ஊட்டத்திலிருந்து உங்கள் பெயரை மறைக்கவும்.',
    shareLocationData: 'இருப்பிடத் தரவைப் பகிரவும்',
    shareLocationDataDesc: 'நகர திட்டமிடுபவர்களுக்கு உதவவும்.',
    appPreferences: 'பயன்பாட்டு விருப்பங்கள்',
    theme: 'தீம் (Theme)',
    systemDefaultDark: 'கணினி இயல்புநிலை (இருண்டது)',
    highContrast: 'அதிக மாறுபாடு (High Contrast)',
    language: 'மொழி (Language)',
    dangerZone: 'ஆபத்து மண்டலம் (Danger Zone)',
    deleteAccount: 'கணக்கை நீக்கு',
    deleteAccountWarning: 'உங்கள் கணக்கு மற்றும் அனைத்து அறிக்கைகளையும் நிரந்தரமாக நீக்கவும். இதை மாற்ற முடியாது.',
    saved: 'சேமிக்கப்பட்டது!',
    supportTitle: 'உதவி & ஆதரவு',
    emergency: 'அவசர சேவைகள்',
    policeFireMedical: 'காவல்துறை / தீயணைப்பு / மருத்துவம்',
    nonEmergencyPolice: 'அவசரமற்ற காவல்துறை',
    contactUs: 'எங்களைத் தொடர்பு கொள்ளவும்',
    emailSupport: 'மின்னஞ்சல் ஆதரவு',
    liveChat: 'நேரலை அரட்டை',
    liveChatHours: 'காலை 9 முதல் மாலை 5 வரை கிடைக்கும்',
    faqTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள் (FAQ)',
    sendFeedback: 'கருத்து அனுப்பவும்',
    sendFeedbackSubtitle: 'சிக்கல் உள்ளதா அல்லது யோசனை உள்ளதா? எங்கள் குழுவிற்கு தெரிவிக்கவும்.',
    message: 'செய்தி',
    describeIssuePlaceholder: 'உங்கள் கருத்து அல்லது சிக்கலை விவரிக்கவும்...',
    submitFeedback: 'கருத்தைச் சமர்ப்பிக்கவும்',
    faq1Q: 'நான் சமர்ப்பித்த அறிக்கையை எவ்வாறு கண்காணிப்பது?',
    faq1A: "பக்கப்பட்டியில் உள்ள 'எனது கண்காணிப்பு' பகுதிக்குச் செல்லவும். அங்கு உங்கள் அறிக்கைகளின் தற்போதைய நிலையை நீங்கள் காணலாம்.",
    faq2Q: 'எனது அடையாளம் பொதுமக்களுக்குத் தெரியுமா?',
    faq2A: "இல்லை. நீங்கள் அமைப்புகளில் மாற்றும் வரை, உங்கள் அறிக்கைகள் 'பெயரற்ற குடிமகன்' என்றே தோன்றும்.",
    faq3Q: 'கடுமையான அவசரநிலையில் நான் என்ன செய்ய வேண்டும்?',
    faq3A: 'அர்பன் ஐ அவசரமற்ற உள்கட்டமைப்பு புகார்களுக்கு மட்டுமே. உயிருக்கு ஆபத்தான அவசரநிலைகளில் உடனடியாக அவசர சேவைகளை (112) அழைக்கவும்.',
    incidentInspection: 'சம்பவ ஆய்வு',
    officialDispatch: 'அதிகாரப்பூர்வ மாநகராட்சி அனுப்புதல்',
    deleteReport: 'அறிக்கையை நீக்கு',
    downloadPdf: 'பிடிஎஃப் பதிவிறக்கு',
    generating: 'உருவாக்குகிறது...',
    editFormalLetter: 'புகார் கடிதத்தைத் திருத்து',
    saveFormalLetter: 'கடிதத்தைச் சேமி',
    resetOfficialTemplate: 'படிவத்தை மீட்டமை',
    copyLetter: 'கடிதத்தை நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    status: 'தற்போதைய நிலை',
    assignedDepartment: 'ஒதுக்கப்பட்ட துறை',
    reportedBy: 'புகாரளித்தவர்',
    dateReported: 'புகாரளிக்கப்பட்ட தேதி',
    locationCoordinates: 'இருப்பிட ஆயத்தொலைவுகள்',
    viewOnGoogleMaps: 'கூகிள் வரைபடத்தில் காண்க',
    verifiedReports: 'சரிபார்க்கப்பட்ட புகார்கள்',
    incidentRecord: 'பதிவு',
    severityLevel: 'தீவிரத்தன்மை நிலை',
    incidentStatus: 'புகாரின் நிலை',
    verifiableDispatchSent: 'மின்னஞ்சல் அனுப்பப்பட்டது',
    openEmailPreview: 'மின்னஞ்சல் முன்னோட்டத்தைத் திறக்கவும்',
    editLetterHelp: 'பிடிஎஃப் பதிவிறக்குவதற்கு முன் இந்த புகார் கடிதத்தில் நீங்கள் மாற்றங்களைச் செய்யலாம்.',
    adminStatusTriage: 'நிர்வாக நிலை மேலாண்மை',
    markNew: 'புதியது',
    markAssigned: 'ஒதுக்கப்பட்டது',
    markResolved: 'தீர்க்கப்பட்டது (அனைவருக்கும் அறிவிக்கவும்)',
    closeInspector: 'மூடு',
    signInSubtitle: 'தொடர உங்கள் குடிமக்கள் போர்ட்டலில் உள்நுழையவும்.',
    emailLogin: 'மின்னஞ்சல் உள்நுழைவு',
    phoneOtp: 'தொலைபேசி (OTP)',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    phoneNumber: 'தொலைபேசி எண்',
    oneTimePassword: 'ஒரு முறை கடவுச்சொல் (OTP)',
    sendVerificationCode: 'சரிபார்ப்புக் குறியீட்டை அனுப்பு',
    verifyAndSignIn: 'சரிபார்த்து உள்நுழைக',
    newToUrbanEye: 'அர்பன் ஐ-க்கு புதியவரா?',
    createAccount: 'கணக்கை உருவாக்கவும்',
    officialAccess: 'அதிகாரப்பூர்வ அணுகல்',
    empoweringCitizens: 'குடிமக்களை மேம்படுத்துதல்.',
    improvingCities: 'நகரங்களை மேம்படுத்துதல்.',
    joinThousands: 'நகர உள்கட்டமைப்பு சிக்கல்களைக் கண்காணிக்கும் ஆயிரக்கணக்கான குடியிருப்பாளர்களுடன் இணையுங்கள்.',
    secureConnection: 'பாதுகாப்பான மற்றும் மறைகுறியாக்கப்பட்ட இணைப்பு',
    citizenRegistration: 'குடிமக்கள் பதிவு',
    alreadyRegistered: 'ஏற்கனவே கணக்கு உள்ளதா?',
    viewAllAlerts: 'அனைத்து எச்சரிக்கைகளையும் காண்க →',
    pinsLive: 'நேரலை ஊசிகள்',
    myLocation: 'எனது இருப்பிடம்',
    radarOn: 'ரேடார் ஆன்',
    radarOff: 'ரேடார் ஆஃப்',
    showCards: 'அட்டைகளைக் காட்டு',
    fullMap: 'முழு வரைபடம்',
    feed: 'ஊட்டம்',
    liveIncidentFeed: 'நேரலை நிகழ்வு ஊட்டம்',
    noIncidentsForFilter: 'தற்போதைய வடிகட்டிக்கு எந்த நிகழ்வும் காணப்படவில்லை.',
    myReportsAndPdf: 'எனது அறிக்கைகள் & PDF',
    inspectIncidentDetails: 'நிகழ்வு விவரங்களை ஆய்வு செய்',
    clickMapToPin: 'குறியிட வரைபடத்தில் கிளிக் செய்யவும்',
    severityTitle: 'தீவிரத்தன்மை',
    allSeverities: 'அனைத்து தீவிர நிலைகளும்',
    highSeverity: 'அதிதீவிரமானது',
    mediumSeverity: 'நடுத்தர தீவிரமானது',
    lowSeverity: 'குறைந்த தீவிரமானது',
    viewPins: 'பின்களைக் காண்க',
    heatmap: 'வெப்ப வரைபடம்',
    allIssues: 'அனைத்து நிகழ்வுகளும்',
    confirmSignOutTitle: 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    confirmSignOutDesc: 'உங்கள் தற்போதைய அமர்வை முடிக்க விரும்புகிறீர்களா? உங்கள் டாஷ்போர்டை அணுக நீங்கள் மீண்டும் உள்நுழைய வேண்டும்.',
    yesSignOut: 'ஆம், வெளியேறு',
    noCancel: 'இல்லை, ரத்துசெய்',
    signOutSecurely: 'பாதுகாப்பாக வெளியேறவும்',
    continueWithGoogle: 'கூகிள் மூலம் தொடரவும்',
    googleSignIn: 'கூகிள் மூலம் உள்நுழைக',
    googleSignUp: 'கூகிள் மூலம் பதிவு செய்யவும்',
    orContinueWith: 'அல்லது இதன் மூலம் தொடரவும்',
    orRegisterWithEmail: 'அல்லது மின்னஞ்சல் மூலம் பதிவு செய்க',
    googleAuthSuccess: 'கூகிள் அங்கீகாரம் வெற்றிகரமாக முடிந்தது',
    googleAuthFailed: 'கூகிள் அங்கீகாரம் தோல்வியடைந்தது',
    verifyEmailTitle: 'உங்கள் மின்னஞ்சலை சரிபார்க்கவும்',
    verifyEmailSubtitle: 'நாங்கள் 6 இலக்க சரிபார்ப்புக் குறியீட்டை அனுப்பியுள்ளோம்:',
    enterOtpCode: '6 இலக்க OTP குறியீட்டை உள்ளிடவும்',
    verifyAndCreate: 'சரிபார்த்து கணக்கை உருவாக்கவும்',
    resendOtp: 'குறியீட்டை மீண்டும் அனுப்பு',
    otpResent: 'சரிபார்ப்புக் குறியீடு மீண்டும் அனுப்பப்பட்டது!',
    invalidOtp: 'தவறான அல்லது காலாவதியான OTP குறியீடு. சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    verifyingOtp: 'சரிபார்க்கிறது...',
    didNotReceiveCode: 'குறியீடு கிடைக்கவில்லையா?',
    resendIn: 'மீண்டும் அனுப்ப'
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      const stored = localStorage.getItem('urban_eye_lang');
      if (stored === 'hi' || stored === 'en') return stored;
      const navLang = (navigator.language || '').toLowerCase();
      if (navLang.startsWith('hi')) return 'hi';
      return 'en';
    } catch {
      return 'en';
    }
  });

  const changeLanguage = (newLang) => {
    if (newLang === 'en' || newLang === 'hi') {
      setLang(newLang);
      try {
        localStorage.setItem('urban_eye_lang', newLang);
        document.documentElement.lang = newLang;
      } catch {}
    }
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  // Translation helper function with fallback
  const t = (key, fallback = '') => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || fallback || key;
  };

  const value = {
    lang,
    setLang: changeLanguage,
    t,
    supportedLanguages: SUPPORTED_LANGUAGES,
    currentLanguageName: SUPPORTED_LANGUAGES.find(l => l.code === lang)?.native || 'English'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
